### ISSUE TITLE
virtctl console hangs forever after the whole environment runs for several days

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt#1058]
The default project shows in openshift web console is `created 5 days ago`, so the cluster is running about 5 days. `virtctl console` works after the cluster is up, but now it just hangs forever, even `Ctrl + C` and `Ctrl + ]` not work. I have seen this issue for several times, so it should not be a occasional issue. 

I checked the pod logs and can't find any clue.

```
# oc version
oc v3.10.0-0.47.0
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

```
# oc logs virt-launcher-fedora-qsj8d -c compute
level=info timestamp=2018-05-22T06:54:45.232376Z pos=virt-launcher.go:141 component=virt-launcher msg="Watchdog file created at /var/run/kubevirt/watchdog-files/golden-images_fedora"
level=info timestamp=2018-05-22T06:54:45.232724Z pos=client.go:152 component=virt-launcher msg="Registered libvirt event notify callback"
level=info timestamp=2018-05-22T06:54:45.232864Z pos=virt-launcher.go:59 component=virt-launcher msg="Marked as ready"
level=info timestamp=2018-05-22T06:54:45.233003Z pos=monitor.go:253 component=virt-launcher msg="Monitoring loop: rate 1s start timeout 5m0s"
level=info timestamp=2018-05-22T06:54:46.234848Z pos=monitor.go:209 component=virt-launcher msg="Still missing PID for qemu, Process qemu not found in /proc"
level=info timestamp=2018-05-22T06:54:47.234328Z pos=monitor.go:209 component=virt-launcher msg="Still missing PID for qemu, Process qemu not found in /proc"
level=error timestamp=2018-05-22T06:54:47.654246Z pos=network.go:151 component=virt-launcher msg="Updated Mac for iface: eth0 - 8a:3f:58:68:90:b8"
level=info timestamp=2018-05-22T06:54:47.657329Z pos=network.go:198 component=virt-launcher msg="Found nameservers in /etc/resolv.conf: \nI\u0002\u0005"
level=info timestamp=2018-05-22T06:54:47.657376Z pos=network.go:199 component=virt-launcher msg="Found search domains in /etc/resolv.conf: golden-images.svc.cluster.local svc.cluster.local cluster.local eng.pek2.redhat.com rhts.eng.pek2.redhat.com"
level=info timestamp=2018-05-22T06:54:47.657406Z pos=dhcp.go:58 component=virt-launcher msg="Starting SingleClientDHCPServer"
level=info timestamp=2018-05-22T06:54:47.699842Z pos=manager.go:145 component=virt-launcher namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Domain defined."
level=info timestamp=2018-05-22T06:54:47.700047Z pos=client.go:136 component=virt-launcher msg="Libvirt event 0 with reason 0 received"
level=info timestamp=2018-05-22T06:54:48.030595Z pos=client.go:119 component=virt-launcher msg="domain status: 3:11"
level=info timestamp=2018-05-22T06:54:48.033954Z pos=client.go:145 component=virt-launcher msg="processed event"
level=info timestamp=2018-05-22T06:54:48.191518Z pos=client.go:136 component=virt-launcher msg="Libvirt event 4 with reason 0 received"
level=info timestamp=2018-05-22T06:54:48.217886Z pos=manager.go:176 component=virt-launcher namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Domain started."
level=info timestamp=2018-05-22T06:54:48.218932Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T06:54:48.219254Z pos=client.go:119 component=virt-launcher msg="domain status: 1:1"
level=info timestamp=2018-05-22T06:54:48.221285Z pos=client.go:145 component=virt-launcher msg="processed event"
level=info timestamp=2018-05-22T06:54:48.221342Z pos=client.go:136 component=virt-launcher msg="Libvirt event 2 with reason 0 received"
level=info timestamp=2018-05-22T06:54:48.225700Z pos=client.go:119 component=virt-launcher msg="domain status: 1:1"
level=info timestamp=2018-05-22T06:54:48.226371Z pos=client.go:145 component=virt-launcher msg="processed event"
level=info timestamp=2018-05-22T06:54:48.235032Z pos=monitor.go:222 component=virt-launcher msg="Found PID for qemu: 180"
level=info timestamp=2018-05-22T06:54:48.277827Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T06:54:48.282892Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T07:02:51.368685Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T07:16:46.420474Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T07:31:48.445984Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T07:41:42.480477Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T07:50:10.550638Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T08:04:26.573751Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T08:19:17.661189Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T08:32:19.760636Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T08:41:24.775775Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T08:49:37.846603Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T09:04:05.877241Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T09:17:04.930690Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T09:28:34.994380Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T09:40:57.035849Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T09:48:35.124404Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T10:03:12.171622Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T10:17:24.219308Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T10:29:04.320828Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T10:38:35.380492Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T10:53:24.450299Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T11:11:24.506459Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T11:21:20.579315Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T11:30:30.635328Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T11:40:18.655173Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T12:07:51.774399Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T12:22:30.874790Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T12:32:19.894640Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T12:38:14.962493Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T12:53:58.080705Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
level=info timestamp=2018-05-22T13:10:08.180360Z pos=server.go:65 component=virt-launcher namespace=golden-images name=fedora kind=VirtualMachine uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synced vm"
```
```
# oc logs -n kube-system virt-handler-5n26c
level=info timestamp=2018-05-22T06:17:17.021801Z pos=virt-handler.go:83 component=virt-handler hostname=dell-per630-04.rhts.eng.pek2.redhat.com
level=info timestamp=2018-05-22T06:17:17.024618Z pos=vm.go:205 component=virt-handler msg="Starting virt-handler controller."
level=info timestamp=2018-05-22T06:17:17.024971Z pos=cache.go:151 component=virt-handler msg="Synchronizing domains"
level=info timestamp=2018-05-22T06:17:17.025163Z pos=cache.go:121 component=virt-handler msg="List domains from sock /var/run/kubevirt/sockets/golden-images_fedora-ephemeral_sock"
level=error timestamp=2018-05-22T06:17:17.025311Z pos=cache.go:124 component=virt-handler reason="dial unix /var/run/kubevirt/sockets/golden-images_fedora-ephemeral_sock: connect: connection refused" msg="failed to connect to cmd client socket"
level=info timestamp=2018-05-22T06:17:17.025336Z pos=cache.go:121 component=virt-handler msg="List domains from sock /var/run/kubevirt/sockets/golden-images_fedora28_sock"
level=error timestamp=2018-05-22T06:17:17.025417Z pos=cache.go:124 component=virt-handler reason="dial unix /var/run/kubevirt/sockets/golden-images_fedora28_sock: connect: connection refused" msg="failed to connect to cmd client socket"
level=info timestamp=2018-05-22T06:17:17.025435Z pos=cache.go:121 component=virt-handler msg="List domains from sock /var/run/kubevirt/sockets/golden-images_fedora_sock"
level=error timestamp=2018-05-22T06:17:17.025502Z pos=cache.go:124 component=virt-handler reason="dial unix /var/run/kubevirt/sockets/golden-images_fedora_sock: connect: connection refused" msg="failed to connect to cmd client socket"
level=info timestamp=2018-05-22T06:17:17.025519Z pos=cache.go:121 component=virt-handler msg="List domains from sock /var/run/kubevirt/sockets/golden-images_ovm-cirros_sock"
level=error timestamp=2018-05-22T06:17:17.025562Z pos=cache.go:124 component=virt-handler reason="dial unix /var/run/kubevirt/sockets/golden-images_ovm-cirros_sock: connect: connection refused" msg="failed to connect to cmd client socket"
level=info timestamp=2018-05-22T06:17:17.025579Z pos=cache.go:121 component=virt-handler msg="List domains from sock /var/run/kubevirt/sockets/golden-images_testvm-ephemeral_sock"
level=error timestamp=2018-05-22T06:17:17.025623Z pos=cache.go:124 component=virt-handler reason="dial unix /var/run/kubevirt/sockets/golden-images_testvm-ephemeral_sock: connect: connection refused" msg="failed to connect to cmd client socket"
level=info timestamp=2018-05-22T06:17:17.025639Z pos=cache.go:121 component=virt-handler msg="List domains from sock /var/run/kubevirt/sockets/golden-images_testvm-nocloud_sock"
level=error timestamp=2018-05-22T06:17:17.025682Z pos=cache.go:124 component=virt-handler reason="dial unix /var/run/kubevirt/sockets/golden-images_testvm-nocloud_sock: connect: connection refused" msg="failed to connect to cmd client socket"
level=info timestamp=2018-05-22T06:17:17.025698Z pos=cache.go:121 component=virt-handler msg="List domains from sock /var/run/kubevirt/sockets/kubevirt-test-default_testvmp2qzq_sock"
level=error timestamp=2018-05-22T06:17:17.025751Z pos=cache.go:124 component=virt-handler reason="dial unix /var/run/kubevirt/sockets/kubevirt-test-default_testvmp2qzq_sock: connect: connection refused" msg="failed to connect to cmd client socket"
level=info timestamp=2018-05-22T06:17:17.025770Z pos=cache.go:121 component=virt-handler msg="List domains from sock /var/run/kubevirt/sockets/kubevirt-test-default_testvmph95d_sock"
level=error timestamp=2018-05-22T06:17:17.025821Z pos=cache.go:124 component=virt-handler reason="dial unix /var/run/kubevirt/sockets/kubevirt-test-default_testvmph95d_sock: connect: connection refused" msg="failed to connect to cmd client socket"
level=info timestamp=2018-05-22T06:17:17.025858Z pos=cache.go:121 component=virt-handler msg="List domains from sock /var/run/kubevirt/sockets/kubevirt-test-default_testvmsct7l_sock"
level=error timestamp=2018-05-22T06:17:17.025902Z pos=cache.go:124 component=virt-handler reason="dial unix /var/run/kubevirt/sockets/kubevirt-test-default_testvmsct7l_sock: connect: connection refused" msg="failed to connect to cmd client socket"
level=info timestamp=2018-05-22T06:17:17.025919Z pos=cache.go:121 component=virt-handler msg="List domains from sock /var/run/kubevirt/sockets/kubevirt-test-default_testvmxc2fd_sock"
level=error timestamp=2018-05-22T06:17:17.025963Z pos=cache.go:124 component=virt-handler reason="dial unix /var/run/kubevirt/sockets/kubevirt-test-default_testvmxc2fd_sock: connect: connection refused" msg="failed to connect to cmd client socket"
level=info timestamp=2018-05-22T06:54:47.634388Z pos=vm.go:382 component=virt-handler namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Processing vm update"
level=info timestamp=2018-05-22T06:54:48.033526Z pos=server.go:75 component=virt-handler msg="Received Domain Event of type ADDED"
level=info timestamp=2018-05-22T06:54:48.033755Z pos=vm.go:648 component=virt-handler namespace=golden-images name=fedora kind=Domain uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Domain is in state Paused reason Unknown"
level=info timestamp=2018-05-22T06:54:48.220599Z pos=vm.go:406 component=virt-handler namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synchronization loop succeeded."
level=info timestamp=2018-05-22T06:54:48.220696Z pos=vm.go:385 component=virt-handler namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="No update processing required"
level=info timestamp=2018-05-22T06:54:48.221026Z pos=server.go:75 component=virt-handler msg="Received Domain Event of type MODIFIED"
level=info timestamp=2018-05-22T06:54:48.221175Z pos=vm.go:679 component=virt-handler namespace=golden-images name=fedora kind=Domain uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Domain is in state Running reason Unknown"
level=info timestamp=2018-05-22T06:54:48.226199Z pos=server.go:75 component=virt-handler msg="Received Domain Event of type MODIFIED"
level=info timestamp=2018-05-22T06:54:48.233309Z pos=vm.go:406 component=virt-handler namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Synchronization loop succeeded."
level=info timestamp=2018-05-22T06:54:48.233371Z pos=vm.go:385 component=virt-handler namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="No update processing required"
level=error timestamp=2018-05-22T06:54:48.276122Z pos=vm.go:397 component=virt-handler namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e reason="Operation cannot be fulfilled on virtualmachines.kubevirt.io \"fedora\": the object has been modified; please apply your changes to the latest version and try again" msg="Updating the VM status failed."
level=info timestamp=2018-05-22T06:54:48.276192Z pos=vm.go:244 component=virt-handler reason="Operation cannot be fulfilled on virtualmachines.kubevirt.io \"fedora\": the object has been modified; please apply your changes to the latest version and try again" msg="re-enqueuing VirtualMachine golden-images/fedora"
level=info timestamp=2018-05-22T06:54:48.276274Z pos=vm.go:382 component=virt-handler namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Processing vm update"
```
```
# oc logs -n kube-system virt-controller-65bd46d9f5-lbdb6
level=info timestamp=2018-05-22T06:16:55.760659Z pos=application.go:149 component=virt-controller service=http action=listening interface=0.0.0.0 port=8182
[root@dell-per630-04 ~]# oc logs -n kube-system virt-controller-65bd46d9f5-48spf
level=info timestamp=2018-05-22T06:16:52.444150Z pos=application.go:149 component=virt-controller service=http action=listening interface=0.0.0.0 port=8182
level=info timestamp=2018-05-22T06:17:10.083319Z pos=virtinformers.go:99 component=virt-controller service=http msg="STARTING informer kubeVirtNodeInformer"
level=info timestamp=2018-05-22T06:17:10.083354Z pos=virtinformers.go:99 component=virt-controller service=http msg="STARTING informer vmPresetInformer"
level=info timestamp=2018-05-22T06:17:10.083367Z pos=virtinformers.go:99 component=virt-controller service=http msg="STARTING informer vmrsInformer"
level=info timestamp=2018-05-22T06:17:10.083376Z pos=virtinformers.go:99 component=virt-controller service=http msg="STARTING informer ovmInformer"
level=info timestamp=2018-05-22T06:17:10.083385Z pos=virtinformers.go:99 component=virt-controller service=http msg="STARTING informer vmInformer"
level=info timestamp=2018-05-22T06:17:10.083395Z pos=virtinformers.go:99 component=virt-controller service=http msg="STARTING informer kubeVirtPodInformer"
level=info timestamp=2018-05-22T06:17:10.083425Z pos=ovm.go:85 component=virt-controller service=http msg="Starting OfflineVirtualMachine controller."
level=info timestamp=2018-05-22T06:17:10.085002Z pos=node.go:101 component=virt-controller service=http msg="Starting node controller."
level=info timestamp=2018-05-22T06:17:10.085034Z pos=vm.go:127 component=virt-controller service=http msg="Starting vm controller."
level=info timestamp=2018-05-22T06:17:10.085056Z pos=replicaset.go:111 component=virt-controller service=http msg="Starting VirtualMachineReplicaSet controller."
level=info timestamp=2018-05-22T06:17:10.085088Z pos=preset.go:69 component=virt-controller service=http msg="Starting Virtual Machine Initializer."
level=info timestamp=2018-05-22T06:52:41.680442Z pos=ovm.go:135 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Started processing OVM"
level=info timestamp=2018-05-22T06:52:41.680543Z pos=ovm.go:186 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Creating or the VM: false"
level=info timestamp=2018-05-22T06:52:41.680616Z pos=ovm.go:261 component=virt-controller service=http msg="vm is nil"
level=info timestamp=2018-05-22T06:52:47.546421Z pos=ovm.go:135 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Started processing OVM"
level=info timestamp=2018-05-22T06:52:47.546523Z pos=ovm.go:186 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Creating or the VM: true"
level=info timestamp=2018-05-22T06:52:47.546572Z pos=ovm.go:376 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Setting stabile UUID '98f07cdd-96da-5880-b6c7-1a5700b73dc4' (was '')"
level=info timestamp=2018-05-22T06:52:47.555066Z pos=ovm.go:458 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Looking for VM Ref"
level=info timestamp=2018-05-22T06:52:47.555119Z pos=ovm.go:469 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="VirtualMachine created bacause fedora was added."
level=info timestamp=2018-05-22T06:52:47.555109Z pos=preset.go:136 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Initializing VirtualMachine"
level=info timestamp=2018-05-22T06:52:47.555141Z pos=ovm.go:135 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Started processing OVM"
level=info timestamp=2018-05-22T06:52:47.555167Z pos=ovm.go:186 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Creating or the VM: true"
level=info timestamp=2018-05-22T06:52:47.555165Z pos=preset.go:156 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=bc94f430-5d8c-11e8-a537-44a842130b3e msg="Marking VM as initialized"
level=info timestamp=2018-05-22T06:52:47.594535Z pos=ovm.go:135 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Started processing OVM"
level=info timestamp=2018-05-22T06:52:47.594581Z pos=ovm.go:186 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Creating or the VM: true"
level=info timestamp=2018-05-22T06:52:47.665970Z pos=ovm.go:135 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Started processing OVM"
level=info timestamp=2018-05-22T06:52:47.666020Z pos=ovm.go:186 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Creating or the VM: true"
level=info timestamp=2018-05-22T06:52:47.685961Z pos=vm.go:155 component=virt-controller service=http reason="Operation cannot be fulfilled on virtualmachines.kubevirt.io \"fedora\": the object has been modified; please apply your changes to the latest version and try again" msg="reenqueuing VM golden-images/fedora"
level=info timestamp=2018-05-22T06:52:47.707009Z pos=ovm.go:135 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Started processing OVM"
level=info timestamp=2018-05-22T06:52:47.707056Z pos=ovm.go:186 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Creating or the VM: true"
level=info timestamp=2018-05-22T06:52:47.714629Z pos=vm.go:155 component=virt-controller service=http reason="Operation cannot be fulfilled on virtualmachines.kubevirt.io \"fedora\": the object has been modified; please apply your changes to the latest version and try again" msg="reenqueuing VM golden-images/fedora"
level=info timestamp=2018-05-22T06:54:47.633782Z pos=ovm.go:135 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Started processing OVM"
level=info timestamp=2018-05-22T06:54:47.633829Z pos=ovm.go:186 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Creating or the VM: true"
level=info timestamp=2018-05-22T06:54:48.233536Z pos=ovm.go:135 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Started processing OVM"
level=info timestamp=2018-05-22T06:54:48.233602Z pos=ovm.go:186 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Creating or the VM: true"
level=info timestamp=2018-05-22T06:54:48.284794Z pos=ovm.go:135 component=virt-controller service=http namespace=golden-images name=fedora kind= uid=b9150d42-5d8c-11e8-a537-44a842130b3e msg="Started processing OVM"
```

**Comment by debianmaster** [comment]
i see same issue  @gouyang 
virt console hangs forever

**Comment by gouyang** [comment]
@debianmaster good to know. Although virtctl console is hanging, but the VM itself is actually running and I could be able to ssh to the VM.

**Comment by rmohr** [comment]
@gouyang can you still access the vm via vnc (`virtctl vnc`)? Could you share the virt-api logs? Which version are you using?

**Comment by rmohr** [comment]
@gouyang while debugging #1061 I experienced this crash in virt-api:

```
2018/05/23 08:43:24 http: panic serving 10.128.0.1:52912: assignment to entry in nil map
goroutine 4867 [running]:
net/http.(*conn).serve.func1(0xc42042caa0)
	/gimme/.gimme/versions/go1.10.linux.amd64/src/net/http/server.go:1726 +0xd0
panic(0x1007080, 0x123b5b0)
	/gimme/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x229
kubevirt.io/kubevirt/pkg/virt-api/rest.(*authorizor).getUserExtras(0xc4200cb800, 0xc420361710, 0x11448d6)
	/root/go/src/kubevirt.io/kubevirt/pkg/virt-api/rest/authorizer.go:93 +0x100
kubevirt.io/kubevirt/pkg/virt-api/rest.(*authorizor).generateAccessReview(0xc4200cb800, 0xc420361a10, 0x1148fb8, 0x7, 0xc420455730)
	/root/go/src/kubevirt.io/kubevirt/pkg/virt-api/rest/authorizer.go:152 +0x15f
kubevirt.io/kubevirt/pkg/virt-api/rest.(*authorizor).Authorize(0xc4200cb800, 0xc420361a10, 0x0, 0x1145375, 0x3, 0x0, 0x0)
	/root/go/src/kubevirt.io/kubevirt/pkg/virt-api/rest/authorizer.go:229 +0xa0
kubevirt.io/kubevirt/pkg/virt-api.(*virtAPIApp).Compose.func1(0xc420361a10, 0xc420197420, 0xc420361aa0)
	/root/go/src/kubevirt.io/kubevirt/pkg/virt-api/api.go:300 +0x52
kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc420361aa0, 0xc420361a10, 0xc420197420)
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful.(*Container).OPTIONSFilter(0xc4200ec1b0, 0xc420361a10, 0xc420197420, 0xc420361aa0)
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful/options_filter.go:15 +0x6d
kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful.(*Container).OPTIONSFilter-fm(0xc420361a10, 0xc420197420, 0xc420361aa0)
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful/options_filter.go:33 +0x48
kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc420361aa0, 0xc420361a10, 0xc420197420)
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
kubevirt.io/kubevirt/pkg/rest/filter.RequestLoggingFilter.func1(0xc420361a10, 0xc420197420, 0xc420361aa0)
	/root/go/src/kubevirt.io/kubevirt/pkg/rest/filter/filter.go:38 +0x8e
kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc420361aa0, 0xc420361a10, 0xc420197420)
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4200ec1b0, 0x1251ce0, 0xc4203ae460, 0xc420509800)
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful/container.go:279 +0x889
kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful.(*Container).(kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x1251ce0, 0xc4203ae460, 0xc420509800)
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420455960, 0x1251ce0, 0xc4203ae460, 0xc420509800)
	/gimme/.gimme/versions/go1.10.linux.amd64/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0x1923fe0, 0x1251ce0, 0xc4203ae460, 0xc420509800)
	/gimme/.gimme/versions/go1.10.linux.amd64/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4200891e0, 0x1251ce0, 0xc4203ae460, 0xc420509800)
	/gimme/.gimme/versions/go1.10.linux.amd64/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc42042caa0, 0x12545a0, 0xc4204bf080)
	/gimme/.gimme/versions/go1.10.linux.amd64/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/gimme/.gimme/versions/go1.10.linux.amd64/src/net/http/server.go:2795 +0x27b
```

could you confirm that you see it too in the virt-api logs?

**Comment by gouyang** [comment]
I have destroyed the environment, I've looked into virt-api logs as it's too long so I didn't paste it there. I almost believe I didn't see the crash logs in it. Let's holding on this and I will set it up again to see whether it's still happening. The kubevirt version is `v0.5.0` and openshift version is `v3.10.0-0.47.0`.

**Comment by rmohr** [comment]
Can you use pre-releases too? E.g. `v0.5.1-alpha.2`?
