### ISSUE TITLE
Kubevirt 1.1.0 create vm Error

### ISSUE THREAD

**Issue by liyang516** [kubevirt/kubevirt#10703]
**What happened:**
Once I create a vm ，the virt-launcher pod is Error.  It seems that the guest-console-log  container occur error.

**What you expected to happen**
Create VM completed with Succeed status.

**How to **reproduce** it (as minimally and precisely as possible):**
create a VM

**Environment**

- KubeVirt version (use virtctl version): v1.1.0
- Kubernetes version (use kubectl version): v1.28.2
- Storage class: csi-rbd-sc
- VM yaml:
```shell
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1
spec:
  dataVolumeTemplates:
  - metadata:
      name: vm1-rootdisk
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: csi-rbd-sc
        volumeMode: Block
      source:
        pvc:
          name: cirros-0.4.0
  runStrategy: Always
  template:
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: scsi
            name: rootdisk
          interfaces:
          - bridge: {}
            name: eth0
        machine:
          type: q35
        memory:
          guest: 4Gi
        resources:
          requests:
            memory: 4Gi
      networks:
      - pod: {}
        name: eth0
      volumes:
      - dataVolume:
          name: vm1-rootdisk
        name: rootdisk
      - cloudInitConfigDrive:
          userData: '#cloud-config'
        name: cloudinitvolume
``` 

**Pod log**
```shell
# kubectl get pods 
NAME                      READY   STATUS   RESTARTS   AGE
virt-launcher-vm1-lgt94   1/2     Error    0          4m7s


# kubectl logs virt-launcher-vm1-lgt94  | grep error
{"component":"virt-launcher-monitor","level":"error","msg":"could not create up serial console term file: /var/run/kubevirt-private/06e26514-226f-4fb3-ad02-6360f35efaa5/virt-serial0-log-sigTerm","pos":"virt-launcher-monitor.go:72","reason":"open /var/run/kubevirt-private/06e26514-226f-4fb3-ad02-6360f35efaa5/virt-serial0-log-sigTerm: no such file or directory","timestamp":"2023-11-09T09:17:07.526952Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (dmidecode -q -t 0,1,2,3,4,11,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2750","subcomponent":"libvirt","thread":"41","timestamp":"2023-11-09T09:17:07.630000Z"}
```

**Comment by scydas** [comment]
Hi, can you give me the logs of virt-handler?

**Comment by akalenyu** [comment]
I think these are a red herring. Could you attach the entire virt-launcher log?

**Comment by ianb-mp** [comment]
I'm seeing the same issue: `compute` and `volumecontainerdisk` are running, however vmi is in a failed state due to `guest-console-log` terminating with reason `Error`. Here's the log output for virt-launcher (from k9s utility):

```
compute {"component":"virt-launcher-monitor","level":"error","msg":"could not create up serial console term file: /var/run/kubevirt-private/53f84578-2485-47e3-a70a-9cc2b59cb991/virt-serial0-log-sigTerm","pos": │
│ "virt-launcher-monitor.go:72","reason":"open /var/run/kubevirt-private/53f84578-2485-47e3-a70a-9cc2b59cb991/virt-serial0-log-sigTerm: no such file or directory","timestamp":"2023-12-06T23:30:19.983965Z"}       │
│ compute {"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-12-06T23:30:20.021972Z"}                                         │
│ compute {"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-12-06T23:30:20.02 │
│ 2054Z"}                                                                                                                                                                                                           │
│ compute {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:563","timestamp":"2023-12-06T23:30:20.022 │
│ 377Z"}                                                                                                                                                                                                            │
│ compute {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file  │
│ or directory')","pos":"libvirt.go:571","timestamp":"2023-12-06T23:30:20.022860Z"}                                                                                                                                 │
│ compute {"component":"virt-launcher","level":"info","msg":"libvirt version: 9.5.0, package: 6.el9 (builder@centos.org, 2023-08-25-08:53:56, )","subcomponent":"libvirt","thread":"43","timestamp":"2023-12-06T23: │
│ 30:20.054000Z"}                                                                                                                                                                                                   │
│ compute {"component":"virt-launcher","level":"info","msg":"hostname: testvm","subcomponent":"libvirt","thread":"43","timestamp":"2023-12-06T23:30:20.054000Z"}                                                    │
│ compute {"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /et │
│ c/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"43","timestamp":"2023-12-06T23:30:20.054000Z"}      │
│ compute {"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"li │
│ bvirt","thread":"43","timestamp":"2023-12-06T23:30:20.054000Z"}                                                                                                                                                   │
│ compute {"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:579","timestamp":"2023-12-06T23:30:20.524518Z"}                                                         │
│ compute {"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:562","timestamp":"2023-12-06T23:30:20.527469Z"}                                             │
│ compute {"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2023-12-06T23:30:20.527709Z"}                                                                │
│ Stream closed EOF for default/virt-launcher-testvm-zkrfl (volumecontainerdisk-init)                                                                                                                               │
│ Stream closed EOF for default/virt-launcher-testvm-zkrfl (container-disk-binary)                                                                                                                                  │
│ Stream closed EOF for default/virt-launcher-testvm-zkrfl (guest-console-log) 
```

After a 1-2 minutes, all containers go to failed state and I see this in the log:
```
compute panic: timed out waiting for domain to be defined                                                                                                                                                         │
│ compute                                                                                                                                                                                                           │
│ compute goroutine 1 [running]:                                                                                                                                                                                    │
│ compute main.waitForDomainUUID(0xc000302ba0?, 0xc000302a80, 0xc000626000, {0x1f06608, 0xc0002781a0})                                                                                                              │
│ compute     cmd/virt-launcher/virt-launcher.go:255 +0x625                                                                                                                                                         │
│ compute main.main()                                                                                                                                                                                               │
│ compute     cmd/virt-launcher/virt-launcher.go:483 +0x1205                                                                                  
```
I'm using Kubernetes v1.28.3+k3s2

**Comment by mansoncui** [comment]
How was your problem solved?

**Comment by mansoncui** [comment]
How was your problem solved?

**Comment by liyang516** [comment]
> How was your problem solved?

No，I give up to use kubevirt 1.1.0. I'm using 1.0.0 now
