### ISSUE TITLE
Virt-API Permission Denied

### ISSUE THREAD

**Issue by ikandars** [kubevirt/kubevirt#10998]
**What happened**:
virt-api CrashLoopBackOff with the following error logs:

```
kubectl -n kubevirt logs virt-api-657ccf77-tblws
W0110 15:37:57.513783       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0110 15:37:57.515784       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
panic: mkdir /tmp/certsdir744381112: permission denied

goroutine 1 [running]:
kubevirt.io/kubevirt/pkg/virt-api.(*virtAPIApp).Execute(0xc000332420)
	pkg/virt-api/api.go:178 +0x5b9
main.main()
	cmd/virt-api/virt-api.go:37 +0x79
```

**What you expected to happen**:
virt-api pod running

**How to reproduce it (as minimally and precisely as possible)**:
Try to create Kubernetes cluster in Debian 11 with kernel 5.10.0-27-amd64 x86_64

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0 and v1.1.1
- Kubernetes version (use `kubectl version`): v1.28.3
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): Debian 11
- Kernel (e.g. `uname -a`): Linux 5.10.0-27-amd64 x86_64
- Install tools: N/A
- Others: N/A

**Comment by ikandars** [comment]
I think the issue is for my side. Hint to close
