### ISSUE TITLE
Same system UUID shared between nodes when migrate failed 

### ISSUE THREAD

**Issue by HenryGuo1019** [kubevirt/kubevirt#12305]
**What happened**:
I tried to migrate a vm with the same SystemUUID node , I get a error log in virt-luncher and the migration failed , than i tried to fake the systemUUID with mount a temp file to /sys/devices/virtual/dmi/id/product_uuid and /sys/class/dmi/id/product_uuid. The k8s node info has changed to the new systemUUID but i still got the error message in virt-luncger. How virt-luncher check if it is the same node and is there any solutions?
```
# before changed
[root@pkc06 cluster-api-chart]# kubectl get nodes -o yaml | grep UUID 
      systemUUID: 11223344-5566-7788-99aa-bbcc11223344
      systemUUID: 11223344-5566-7788-99aa-bbcc11223344

# after changed 
[root@pkc06 cluster-api-chart]# kubectl get nodes -o yaml | grep UUID 
      systemUUID: 11223344-5566-7788-99aa-bbcc22334455
      systemUUID: 11223344-5566-7788-99aa-bbcc11223344

# error log in virt-lunvher 
{"component":"virt-launcher","level":"info","msg":"cookielen=740 cookie='<qemu-migration>","pos":"qemuMigrationCookieParse:1511","subcomponent":"libvirt","thread":"26","timestamp":"2024-07-09T08:49:22.942000Z"}
{"component":"virt-launcher","level":"info","msg":"  <name>xcloud-default_cirros1</name>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942395Z"}
{"component":"virt-launcher","level":"info","msg":"  <uuid>3df3b144-362a-5efb-8d26-acbb926fa216</uuid>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942412Z"}
{"component":"virt-launcher","level":"info","msg":"  <hostname>cirros1</hostname>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942431Z"}
{"component":"virt-launcher","level":"info","msg":"  <hostuuid>11223344-5566-7788-99aa-bbcc11223344</hostuuid>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942444Z"}
{"component":"virt-launcher","level":"info","msg":"  <feature name='lockstate'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942457Z"}
{"component":"virt-launcher","level":"info","msg":"  <capabilities>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942471Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='xbzrle' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942485Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='auto-converge' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942498Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='rdma-pin-all' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942512Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='postcopy-ram' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942526Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='compress' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942540Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='pause-before-switchover' auto='yes'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942553Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='late-block-activate' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942567Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='multifd' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942582Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='dirty-bitmaps' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942599Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='return-path' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942613Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='zero-copy-send' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942627Z"}
{"component":"virt-launcher","level":"info","msg":"  </capabilities>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942640Z"}
{"component":"virt-launcher","level":"info","msg":"</qemu-migration>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942653Z"}
{"component":"virt-launcher","level":"info","msg":"'","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.942667Z"}
{"component":"virt-launcher","level":"info","msg":"xml=<qemu-migration>","pos":"qemuMigrationCookieXMLParseStr:1418","subcomponent":"libvirt","thread":"26","timestamp":"2024-07-09T08:49:22.943000Z"}
{"component":"virt-launcher","level":"info","msg":"  <name>xcloud-default_cirros1</name>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943139Z"}
{"component":"virt-launcher","level":"info","msg":"  <uuid>3df3b144-362a-5efb-8d26-acbb926fa216</uuid>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943157Z"}
{"component":"virt-launcher","level":"info","msg":"  <hostname>cirros1</hostname>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943174Z"}
{"component":"virt-launcher","level":"info","msg":"  <hostuuid>11223344-5566-7788-99aa-bbcc11223344</hostuuid>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943188Z"}
{"component":"virt-launcher","level":"info","msg":"  <feature name='lockstate'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943202Z"}
{"component":"virt-launcher","level":"info","msg":"  <capabilities>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943217Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='xbzrle' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943232Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='auto-converge' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943254Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='rdma-pin-all' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943276Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='postcopy-ram' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943293Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='compress' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943308Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='pause-before-switchover' auto='yes'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943326Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='late-block-activate' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943340Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='multifd' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943354Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='dirty-bitmaps' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943367Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='return-path' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943381Z"}
{"component":"virt-launcher","level":"info","msg":"    <cap name='zero-copy-send' auto='no'/>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943394Z"}
{"component":"virt-launcher","level":"info","msg":"  </capabilities>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943409Z"}
{"component":"virt-launcher","level":"info","msg":"</qemu-migration>","subcomponent":"libvirt","timestamp":"2024-07-09T08:49:22.943425Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Attempt to migrate guest to the same host 11223344-5566-7788-99aa-bbcc11223344","pos":"qemuMigrationCookieXMLParse:1324","subcomponent":"libvirt","thread":"26","timestamp":"2024-07-09T08:49:22.943000Z"}
{"component":"virt-launcher","level":"info","msg":"conn=0x4000400046b0","pos":"virConnectUnregisterCloseCallback:1548","subcomponent":"libvirt","thread":"27","timestamp":"2024-07-09T08:49:22.944000Z"}
{"component":"virt-launcher","level":"info","msg":"stream=(nil)","pos":"daemonRemoveAllClientStreams:519","subcomponent":"libvirt","thread":"25","timestamp":"2024-07-09T08:49:22.945000Z"}
{"component":"virt-launcher","level":"info","msg":"conn=0x4000400046b0","pos":"virConnectClose:1312","subcomponent":"libvirt","thread":"25","timestamp":"2024-07-09T08:49:22.946000Z"}
{"component":"virt-launcher","level":"info","msg":"conn=0x4000400046b0","pos":"virCloseCallbacksDomainRunForConn:346","subcomponent":"libvirt","thread":"25","timestamp":"2024-07-09T08:49:22.946000Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Signaled target pod virt-launcher-cirros1-ltc66 to cleanup","name":"cirros1","namespace":"xcloud-default","pos":"server.go:154","timestamp":"2024-07-09T08:49:23.532690Z","uid":"93f45040-9024-46ec-8ac3-08ad4b52a44c"}
panic: received early exit signal

goroutine 1 [running]:
main.waitForDomainUUID(0x4000384900?, 0x40003847e0, 0x40003ce5a0, {0x1dbde58, 0x4000270750})
	cmd/virt-launcher/virt-launcher.go:265 +0x348
main.main()
	cmd/virt-launcher/virt-launcher.go:469 +0xe84
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:125","timestamp":"2024-07-09T08:49:24.483110Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:143","timestamp":"2024-07-09T08:49:24.483192Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"error when checking for istio-proxy presence","pos":"virt-launcher-monitor.go:291","reason":"Get \"http://localhost:15021/healthz/ready\": dial tcp [::1]:15021: connect: connection refused","timestamp":"2024-07-09T08:49:24.487914Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"error when checking for istio-proxy presence","pos":"virt-launcher-monitor.go:291","reason":"Get \"http://localhost:15021/healthz/ready\": dial tcp [::1]:15021: connect: connection refused","timestamp":"2024-07-09T08:49:24.538853Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"error when checking for istio-proxy presence","pos":"virt-launcher-monitor.go:291","reason":"Get \"http://localhost:15021/healthz/ready\": dial tcp [::1]:15021: connect: connection refused","timestamp":"2024-07-09T08:49:24.789861Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"error when checking for istio-proxy presence","pos":"virt-launcher-monitor.go:291","reason":"Get \"http://localhost:15021/healthz/ready\": dial tcp [::1]:15021: connect: connection refused","timestamp":"2024-07-09T08:49:26.040989Z"}

```

**What you expected to happen**:
migrate successful even when systemUUID is same between nodes 

**How to reproduce it (as minimally and precisely as possible)**:
k8s cluster with the same systemUUID

**Environment**:
- KubeVirt version (use `virtctl version`):  v1.0.0 
- Kubernetes version (use `kubectl version`): v1.28.3+rke2r2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): uos-20-1060
- Kernel (e.g. `uname -a`): 5.10.0-46.uelc20.aarch64
- Install tools: rke2 
- Others: N/A

**Comment by aburdenthehand** [comment]
/remove-lifecycle stale
cc @iholder101 - Is this something you can help with?

**Comment by iholder101** [comment]
> /remove-lifecycle stale cc @iholder101 - Is this something you can help with?

Yes indeed.
@HenryGuo1019 thanks a lot for this issue!

We are now discussing how to solve it in the following PR: https://github.com/kubevirt/community/pull/347.
Since we'll be discussing this elsewhere, I'll close this issue. Thanks again for reporting it! I engourage you to join the discussion and express your opinions there!

/close
