### ISSUE TITLE
mac computer make compilation error

### ISSUE THREAD

**Issue by xrwang8** [kubevirt/kubevirt#12410]
**What happened**:
I'm using a mac arm architecture computer, and when I compile with make, I get the error
```
Sandbox is up to date
INFO: Repository go_image_base_aarch64 instantiated at:
  /root/go/src/kubevirt.io/kubevirt/WORKSPACE:298:15: in <toplevel>
Repository rule container_pull defined at:
  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/io_bazel_rules_docker/container/pull.bzl:243:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'go_image_base_aarch64':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/io_bazel_rules_docker/container/pull.bzl", line 189, column 13, in _impl
                fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))
Error in fail: Pull command failed: 2024/07/19 07:51:46 Running the Image Puller to pull images from a Docker Registry...
2024/07/19 07:51:46 Image pull was unsuccessful: reading image "gcr.io/distroless/base-debian12@sha256:02e08b836ad99a1de187da19278c5058dc6bf2c62b857d313b6076e0c68c5099": error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
 (/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_puller_linux_arm64/file/downloaded -directory /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base_aarch64/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/base-debian12@sha256:02e08b836ad99a1de187da19278c5058dc6bf2c62b857d313b6076e0c68c5099)
ERROR: /root/go/src/kubevirt.io/kubevirt/WORKSPACE:298:15: fetching container_pull rule //external:go_image_base_aarch64: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/io_bazel_rules_docker/container/pull.bzl", line 189, column 13, in _impl
                fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))
Error in fail: Pull command failed: 2024/07/19 07:51:46 Running the Image Puller to pull images from a Docker Registry...
2024/07/19 07:51:46 Image pull was unsuccessful: reading image "gcr.io/distroless/base-debian12@sha256:02e08b836ad99a1de187da19278c5058dc6bf2c62b857d313b6076e0c68c5099": error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
 (/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_puller_linux_arm64/file/downloaded -directory /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base_aarch64/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/base-debian12@sha256:02e08b836ad99a1de187da19278c5058dc6bf2c62b857d313b6076e0c68c5099)
INFO: Repository checkpolicy-0__3.6-1.el9.aarch64 instantiated at:
  /root/go/src/kubevirt.io/kubevirt/WORKSPACE:847:4: in <toplevel>
Repository rule rpm defined at:
  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/internal/rpm.bzl:48:22: in <toplevel>
INFO: Repository dbus-broker-0__28-7.el9.aarch64 instantiated at:
  /root/go/src/kubevirt.io/kubevirt/WORKSPACE:1153:4: in <toplevel>
Repository rule rpm defined at:
  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/internal/rpm.bzl:48:22: in <toplevel>
INFO: Repository systemd-0__252-33.el9.aarch64 instantiated at:
  /root/go/src/kubevirt.io/kubevirt/WORKSPACE:7039:4: in <toplevel>
Repository rule rpm defined at:
  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/internal/rpm.bzl:48:22: in <toplevel>
INFO: Repository yajl-0__2.1.0-22.el9.aarch64 instantiated at:
  /root/go/src/kubevirt.io/kubevirt/WORKSPACE:7561:4: in <toplevel>
Repository rule rpm defined at:
  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/internal/rpm.bzl:48:22: in <toplevel>
INFO: Repository libvirt-libs-0__10.0.0-7.el9.aarch64 instantiated at:
  /root/go/src/kubevirt.io/kubevirt/WORKSPACE:4600:4: in <toplevel>
Repository rule rpm defined at:
  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/internal/rpm.bzl:48:22: in <toplevel>
INFO: Repository openldap-0__2.6.6-3.el9.aarch64 instantiated at:
  /root/go/src/kubevirt.io/kubevirt/WORKSPACE:5140:4: in <toplevel>
Repository rule rpm defined at:
  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/internal/rpm.bzl:48:22: in <toplevel>
INFO: Repository glib2-0__2.68.4-15.el9.aarch64 instantiated at:
  /root/go/src/kubevirt.io/kubevirt/WORKSPACE:1828:4: in <toplevel>
Repository rule rpm defined at:
  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/internal/rpm.bzl:48:22: in <toplevel>
ERROR: /root/go/src/kubevirt.io/kubevirt/BUILD.bazel:166:16: //:passwd-image depends on @go_image_base_aarch64//image:image in repository @go_image_base_aarch64 which failed to fetch. no such package '@go_image_base_aarch64//image': Pull command failed: 2024/07/19 07:51:46 Running the Image Puller to pull images from a Docker Registry...
2024/07/19 07:51:46 Image pull was unsuccessful: reading image "gcr.io/distroless/base-debian12@sha256:02e08b836ad99a1de187da19278c5058dc6bf2c62b857d313b6076e0c68c5099": error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
 (/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_puller_linux_arm64/file/downloaded -directory /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base_aarch64/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/base-debian12@sha256:02e08b836ad99a1de187da19278c5058dc6bf2c62b857d313b6076e0c68c5099)
ERROR: Analysis of target '//cmd/sidecars:sidecar-shim-image' failed; build aborted: 
INFO: Elapsed time: 20.232s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1100 packages loaded, 7576 targets configured)
    currently loading: @cracklib-dicts-0__2.9.6-27.el9.aarch64//rpm ... (10 packages)
    Fetching @org_golang_x_net; fetching 20s
    Fetching http://mirror.stream.centos.org/9-stream/AppStream/aarch64/os/Packages/libvirt-libs-10.0.0-7.el9.aarch64.rpm; 3,110,466B 13s
    Fetching http://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/glib2-2.68.4-15.el9.aarch64.rpm; 16,384B 12s
    Fetching http://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/checkpolicy-3.6-1.el9.aarch64.rpm; 16,384B 12s
    Fetching @com_github_google_go_containerregistry; fetching 12s
    Fetching http://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/dbus-broker-28-7.el9.aarch64.rpm; 11s
    Fetching http://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/systemd-252-33.el9.aarch64.rpm; 11s
    Fetching http://mirror.stream.centos.org/9-stream/AppStream/aarch64/os/Packages/yajl-2.1.0-22.el9.aarch64.rpm; 11s ... (9 fetches)

What's next:
    Try Docker Debug for seamless, persistent debugging tools in any container or image → docker debug kubevirt-bazel-server
    Learn more at https://docs.docker.com/go/debug-cli/
make: *** [bazel-build] Error 1
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- OS (e.g. from /etc/os-release): MAC

**Comment by Elshirak** [comment]
Hello @xrwang8!

Thank you for reporting! Could you please provide some more information about this issue. I'm interested in your steps. Did you follow the guide from [here?](https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md)

Trying to reproduce this error, it would be grateful to receive your answer :)

**Comment by xpivarc** [comment]
`error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH`  seems to be the root cause
