### ISSUE TITLE
`./tools` folder fails to build with unit tests that are never triggered

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirt#12790]
**What happened**:
As @akalenyu mentions in [this comment](https://github.com/kubevirt/kubevirt/pull/12778#discussion_r1751678770), `./tools` fails to build:
```
kubevirt/tools/util/marshaller_test.go:32:195: not enough arguments in call to components.NewHandlerDaemonSet
```

In addition, as he's pointing out, these tests are not attempted to ever run:
https://github.com/kubevirt/kubevirt/blob/941b04cb9f90745ae2038b13c8bb82eea55a16dd/hack/bazel-test.sh#L7

To add an insult to injury, these are lacking the `*_suite_test.go` that's required to make these tests runnable.

**What you expected to happen**:
The tests should either be able to build and run via `make test` or removed.

**How to reproduce it (as minimally and precisely as possible)**:
Trying to build `./tools`

**Comment by aryandutt** [comment]
Is this a good first issue to work on?

**Comment by iholder101** [comment]
> Is this a good first issue to work on?

@aryandutt Yes, it is :)
Would you like to go ahead and fix it? If you need any help, I'll gladly try to provide it.

**Comment by iholder101** [comment]
@dosu You're pretty close :)

Note that it's possible to use `make generate` to auto-create the `*_suite_test.go` file.

**Comment by aryandutt** [comment]
Hi @iholder101, I would definitely like to work on it!

Could you please give me a brief overview?

Thanks

**Comment by aryandutt** [comment]
Hi @iholder101, is [this](https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md) the file I need to look at to setup the project locally and recreate the issue?

**Comment by iholder101** [comment]
> Hi @iholder101, is [this](https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md?rgh-link-date=2024-09-12T22%3A29%3A58Z) the file I need to look at to setup the project locally and recreate the issue?

Yes, that's a great starting point indeed

**Comment by aryandutt** [comment]
I was trying to setup Kubevirt by looking at the getting started section but I am encountering the following error.

`ERROR: An error occurred during the fetch of repository 'go_image_base_aarch64':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/io_bazel_rules_docker/container/pull.bzl", line 189, column 13, in _impl
                fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))`

**Comment by ronger4** [comment]
> I was trying to setup Kubevirt by looking at the getting started section but I am encountering the following error.
> 
> `ERROR: An error occurred during the fetch of repository 'go_image_base_aarch64': Traceback (most recent call last): File "/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/io_bazel_rules_docker/container/pull.bzl", line 189, column 13, in _impl fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))`

If your still stuck, ping me on slack, I will try help you (I setup kubevirt locally too recently)
If you haven't joined, it's the Kubernetes slack channel.

**Comment by NishantBansal2003** [comment]
> Regarding the fact that it doesn't build, I see that there's a function usage that provide less parameters than whatever's needed there. I assume that someone refactored it and forgot to change the function call? You can try to add the missing parameter there.

Hey @iholder101, So apparently adding missing parameters in `components.NewHandlerDaemonSet` will fix this issue?right?

**Comment by iholder101** [comment]
> > Regarding the fact that it doesn't build, I see that there's a function usage that provide less parameters than whatever's needed there. I assume that someone refactored it and forgot to change the function call? You can try to add the missing parameter there.
> 
> Hey [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/77444623?s=64&amp;u=cef37d0fac406640a472d64a489293700db3446a&amp;v=4">@iholder101](https://github.com/iholder101?rgh-link-date=2024-09-21T05%3A12%3A37.000Z), So apparently adding missing parameters in `components.NewHandlerDaemonSet` will fix this issue?right?

I don't think so as this function is part of virt-operator which is able to build. Can you elaborate?
