### ISSUE TITLE
virt-launcher somtimes panics with prestart hook sidecar in tests

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1696]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

virt-launcher container somtimes crashes when a preStart hook should be executed:

```
Pod name: virt-launcher-testvmitfmbjl896spkmgbdvfs7cdlmzxh62zs8fqmb54kgsj	 Pod phase: Running

{"component":"virt-launcher","level":"info","msg":"Failed to process sidecar socket: smbios.sock","pos":"manager.go:106","reason":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","timestamp":"2018-11-13T13:11:40.626364Z"}
panic: rpc error: code = DeadlineExceeded desc = context deadline exceeded

goroutine 1 [running]:
main.main()
	/root/go/src/kubevirt.io/kubevirt/cmd/virt-launcher/virt-launcher.go:334 +0xf48
{"component":"virt-launcher","level":"error","msg":"dirty virt-launcher shutdown","pos":"virt-launcher.go:483","reason":"exit status 2","timestamp":"2018-11-13T13:11:40.640108Z"}
{"component":"virt-launcher","level":"error","msg":"Failed to reap process -1","pos":"virt-launcher.go:461","reason":"no child processes","timestamp":"2018-11-13T13:11:40.640346Z"}
{{VirtualMachineInstance kubevirt.io/v1alpha2} {testvmitfmbjl896spkmgbdvfs7cdlmzxh62zs8fqmb5gwpp6pmfc2n  kubevirt-test-default /apis/kubevirt.io/v1alpha2/namespaces/kubevirt-test-default/virtualmachineinstances/testvmitfmbjl896spkmgbdvfs7cdlmzxh62zs8fqmb5gwpp6pmfc2n a61d3c71-e745-11e8-a251-525500d15501 8283 1 2018-11-13 13:11:36 +0000 UTC <nil> <nil> map[] map[hooks.kubevirt.io/hookSidecars:[{"image": "registry:5000/kubevirt/example-hook-sidecar:devel", "imagePullPolicy": "IfNotPresent"}] smbios.vm.kubevirt.io/baseBoardManufacturer:Radical Edward] [] nil [foregroundDeleteVirtualMachine] } {{{map[memory:{{64 6} {<nil>} 64M DecimalSI}] map[] false} <nil> <nil> {q35} 0xc4206e1860 <nil> 0xc42088f700 {[{disk0 disk0 {0xc420b882a0 <nil> <nil> <nil>} <nil>  <nil> }] <nil> [{default  {0x1e98a88 <nil>} []  <nil> }] <nil> <nil> <nil> <nil> <nil>} <nil>} map[] nil [] 0xc42075a748 [{disk0 {<nil> nil <nil> 0xc42088f780 <nil> <nil> <nil> <nil> <nil> <nil>}}]   [{default {0xc4206e1880 <nil> <nil>}}]} {  [] Failed [] <nil>}}
â€¢ Failure [182.656 seconds]
HookSidecars
/root/go/src/kubevirt.io/kubevirt/tests/vmi_hook_sidecar_test.go:40
  VMI definition
  /root/go/src/kubevirt.io/kubevirt/tests/vmi_hook_sidecar_test.go:58
    with SM BIOS hook sidecar
    /root/go/src/kubevirt.io/kubevirt/tests/vmi_hook_sidecar_test.go:59
      should call Collect and OnDefineDomain on the hook sidecar [It]
      /root/go/src/kubevirt.io/kubevirt/tests/vmi_hook_sidecar_test.go:67

      Timed out after 90.000s.
      Timed out waiting for VMI to enter Running phase
      Expected
          <bool>: false
      to equal
          <bool>: true

      /root/go/src/kubevirt.io/kubevirt/tests/utils.go:1510
```

**What you expected to happen**:

That virt-launcher does not start or even fail if a preStart hook which should be executed does not work is fine. But at least in this test this is for sure not wanted. It happens too often to be considered a random issue. @phoracek maybe you can have a look?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
@rmohr will do

**Comment by rmohr** [comment]
I did not see the sidecar tests fail for some time now. Anyone else? @cynepco3hahue @davidvossel @slintes ?

**Comment by slintes** [comment]
@rmohr me neither

**Comment by cynepco3hahue** [comment]
@rmohr same for me
