### ISSUE TITLE
segfault if libvirtd is not running

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#18]
The `virt-handler` segfaults with the following trace if libvirtd is not running:

```
 Jan 04 09:12:50 demo.kubevirt.io docker-current[10639]: Hostname: demo.kubevirt.io
Jan 04 09:12:50 demo.kubevirt.io docker-current[10639]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 04 09:12:50 demo.kubevirt.io docker-current[10639]: [signal 0xb code=0x1 addr=0x0 pc=0x40b131]
Jan 04 09:12:50 demo.kubevirt.io docker-current[10639]: 
Jan 04 09:12:50 demo.kubevirt.io docker-current[10639]: goroutine 1 [running]:
Jan 04 09:12:50 demo.kubevirt.io docker-current[10639]: panic(0x18bdea0, 0xc820014070)
Jan 04 09:12:50 demo.kubevirt.io docker-current[10639]:         /home/travis/.gimme/versions/go1.6.3.linux.amd64/src/runtime/panic.go:481 +0x3e6
Jan 04 09:12:50 demo.kubevirt.io docker-current[10639]: main.main()
Jan 04 09:12:50 demo.kubevirt.io docker-current[10639]:         /home/travis/gopath/src/kubevirt.io/kubevirt/cmd/virt-handler/virt-handler.go:50 +0x1341
```

Can this error be made a bit nicer?

**Comment by rmohr** [comment]
That one should be fixed by #33. Tested it also without a running libvirt.
