### ISSUE TITLE
api server logs full failing to fetch subresources

### ISSUE THREAD

**Issue by terinjokes** [kubevirt/kubevirt#2021]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

API Server logs are full of errors attempting to fetch KubeVirt subresources:

```console
I0213 15:33:39.449293       1 wrap.go:42] GET /apis/subresources.kubevirt.io/v1alpha3: (179.004µs) 503
goroutine 768260 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc423db60e0, 0x1f7)
```

These errors persist even if no KubeVirt controllers and no virtualmachine resources are in use.

**What you expected to happen**:

I expect my API Server logs to be much quieter.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.14.0
- Kubernetes version (use `kubectl version`): 1.10.11
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Debian Stretch
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by terinjokes** [comment]
Issues resolved itself.

Something seems to be registering v1alpha2 that doesn't exists, but that might be worth another issue:

```console
I0214 12:37:38.777019       1 wrap.go:42] GET /apis/subresources.kubevirt.io/v1alpha2: (827.515µs) 404 [[kubectl/v1.8.5 (linux/amd64) kubernetes/cce11c6] 10.36.57.26:59622]
```
