### ISSUE TITLE
iptables on OKD

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#2400]
We fail to configure iptables on OKD since they are not initialized on the host (and maybe we are also missing some kernel modules). I think we have two options: Enable and initialize iptables on OKD host **or** use nftables in case we run on OKD.

```
{"component":"virt-launcher","level":"error","msg":"failed to create nat rules for vm error: running [/usr/sbin/iptables -t nat -N KUBEVIRT_PREINBOUND --wait]: exit status 3: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-80.1.2.el8_0.x86_64\niptables v1.6.2: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n","pos":"podinterface.go:435","timestamp":"2019-06-19T14:29:18.393389Z"} {"component":"virt-launcher","level":"fatal","msg":"failed to prepared pod networking","pos":"podinterface.go:88","reason":"running [/usr/sbin/iptables -t nat -N KUBEVIRT_PREINBOUND --wait]: exit status 3: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-80.1.2.el8_0.x86_64\niptables v1.6.2: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n","timestamp":"2019-06-19T14:29:18.393440Z"} panic: running [/usr/sbin/iptables -t nat -N KUBEVIRT_PREINBOUND --wait]: exit status 3: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-80.1.2.el8_0.x86_64 iptables v1.6.2: can't initialize iptables table `nat': Table does not exist (do you need to insmod?) Perhaps iptables or your kernel needs to be upgraded. goroutine 69 [running]: kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/network.(*PodInterface).Plug(0x22a98b0, 0xc000740300, 0xc00014e630, 0xc00034bbf0, 0xc000330000, 0x14dec7d, 0x4, 0x10, 0x12f7140) pkg/virt-launcher/virtwrap/network/podinterface.go:89 +0x536 kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/network.SetupNetworkInterfaces(0xc000740300, 0xc000330000, 0x0, 0x0) pkg/virt-launcher/virtwrap/network/network.go:83 +0x520 kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).preStartHook(0xc0004a9340, 0xc000740300, 0xc000330000, 0x1698e00, 0x0, 0x166c820) pkg/virt-launcher/virtwrap/manager.go:728 +0x3ad kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).SyncVMI(0xc0004a9340, 0xc000740300, 0xc0003ca900, 0x0, 0x0, 0x0) pkg/virt-launcher/virtwrap/manager.go:881 +0x5e2 kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cmd-server.(*Launcher).SyncVirtualMachine(0xc00001c460, 0x1686540, 0xc00034acf0, 0xc00034ad20, 0xc00001c460, 0xc00034ac60, 0x135df40) pkg/virt-launcher/virtwrap/cmd-server/server.go:159 +0x81 kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1._Cmd_SyncVirtualMachine_Handler(0x1426cc0, 0xc00001c460, 0x1686540, 0xc00034acf0, 0xc00073eb40, 0x0, 0x0, 0x0, 0xc000582b00, 0x55c) bazel-out/k8-fastbuild/bin/pkg/handler-launcher-com/cmd/v1/linux_amd64_stripped/kubevirt_cmd_go_proto%!/(MISSING)kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1/cmd.pb.go:515 +0x23e google.golang.org/grpc.(*Server).processUnaryRPC(0xc00046af00, 0x1692140, 0xc00055e180, 0xc000734300, 0xc00049d2c0, 0x21e5760, 0x0, 0x0, 0x0) external/org_golang_google_grpc/server.go:971 +0x4a2 google.golang.org/grpc.(*Server).handleStream(0xc00046af00, 0x1692140, 0xc00055e180, 0xc000734300, 0x0) external/org_golang_google_grpc/server.go:1250 +0xd61 google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000018320, 0xc00046af00, 0x1692140, 0xc00055e180, 0xc000734300) external/org_golang_google_grpc/server.go:690 +0x9f created by google.golang.org/grpc.(*Server).serveStreams.func1 external/org_golang_google_grpc/server.go:688 +0xa1 {"component":"virt-launcher","level":"error","msg":"dirty virt-launcher shutdown","pos":"virt-launcher.go:558","reason":"exit status 2","time
```

Kudos to @cynepco3hahue for reporting the issue.

**Comment by cynepco3hahue** [comment]
Some details regarding the environment where it happened:
```
NAME                          STATUS   ROLES    AGE   VERSION             INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                                                   KERNEL-VERSION               CONTAINER-RUNTIME
test-1-hw7kn-master-0         Ready    master   24h   v1.13.4+9252851b0   192.168.126.11   <none>        Red Hat Enterprise Linux CoreOS 410.8.20190612.0 (Ootpa)   4.18.0-80.1.2.el8_0.x86_64   cri-o://1.13.9-1.rhaos4.1.gitd70609a.el8
test-1-hw7kn-worker-0-7w268   Ready    worker   24h   v1.13.4+9252851b0   192.168.126.51   <none>        Red Hat Enterprise Linux CoreOS 410.8.20190612.0 (Ootpa)   4.18.0-80.1.2.el8_0.x86_64   cri-o://1.13.9-1.rhaos4.1.gitd70609a.el8
```

**Comment by phoracek** [comment]
The log complains about ip_tables module though.

**Comment by cynepco3hahue** [comment]
I meant that it has `iptables` binary but not the module, so I believe we need support for `nf_tables`, likes I said to Petr,  I do not believe that RHCOS will add additional kernel module only because we are working only with `iptables` but we can try to speak with them.

**Comment by cynepco3hahue** [comment]
I think it is an urgent issue because it blocks all functional testing on top of OKD.

**Comment by dankenigsberg** [comment]
@phoracek Why do we touch `iptables`? Only for `masquerade`? Or also for something else?

**Comment by phoracek** [comment]
@dankenigsberg yes, it seems to be only under masquerade code.

**Comment by SchSeba** [comment]
I will take a look on that

**Comment by SchSeba** [comment]
Related to:
* https://bugzilla.redhat.com/show_bug.cgi?id=1708500
* https://github.com/istio/istio/issues/13986

**Comment by fabiand** [comment]
@cynepco3hahue @SchSeba anything blocking this work?

**Comment by SchSeba** [comment]
@fabiand waiting for this PR https://github.com/kubevirt/kubevirt/pull/2487 to be merge and I am fixing the review comments here #2430

**Comment by fabiand** [comment]
Thanks, that does not sound to bad.
