### ISSUE TITLE
virt-operator imageName spec

### ISSUE THREAD

**Issue by lurenjia528** [kubevirt/kubevirt#2455]
I build the image "xxx/xxx/virt-operator-arm64:v0.18.1" , and run failed
``` bash
root@master1:/nas/kubevirt/yaml# kubectl logs virt-operator-6f7b978bff-rsdqc 
{"component":"virt-operator","level":"info","msg":"we are on kubernetes","pos":"application.go:164","timestamp":"2019-07-04T06:04:55.873192Z"}
panic: runtime error: index out of range

goroutine 1 [running]:
kubevirt.io/kubevirt/pkg/virt-operator/util.GetConfig(0x12bd6e0, 0x40007c5ec0, 0x0, 0x0)
	/opt/kubevirt/kubevirt/pkg/virt-operator/util/config.go:54 +0x178
kubevirt.io/kubevirt/pkg/virt-operator.NewKubeVirtController(0x15d93c0, 0x40000dfc80, 0x15af720, 0x400018b0e0, 0x158ebe0, 0x40007cf840, 0x15af6c0, 0x400058c420, 0x15af6c0, 0x400058c600, ...)
	/opt/kubevirt/kubevirt/pkg/virt-operator/kubevirt.go:82 +0x22c
kubevirt.io/kubevirt/pkg/virt-operator.Execute()
	/opt/kubevirt/kubevirt/pkg/virt-operator/application.go:170 +0xd14
main.main()
	/opt/kubevirt/kubevirt/cmd/virt-operator/virt-operator.go:30 +0x20

```
reason as follow:
the reg is strict：

https://github.com/kubevirt/kubevirt/blob/147b09fc228d03e11323595bfbb0ae3cc29c1b81/pkg/virt-operator/util/config.go#L64

**Comment by slintes** [comment]
I guess there are more places in our codebase and build scripts where we assume this pattern for our image names. I suggest to put `arm64` into the tag name. Wdyt?

**Comment by lurenjia528** [comment]
@slintes ok,thanks
