### ISSUE TITLE
Kube apiserver panic'd on GET for virtualmachineinstances

### ISSUE THREAD

**Issue by brysk** [kubevirt/kubevirt#2728]
Hi KubeVIrt Folks,

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I have tried to create configmap but failed with:

```
root@LS-HW-0919B:~/sriov-network-device-plugin# kubectl create -f images/configMap.yaml
Error from server (InternalError): error when creating "images/configMap.yaml": Internal error occurred: resource quota evaluates timeout
```

Checked k8s apis server logs and found that process panic'd when executing GET against VMI:

```E0920 12:51:13.717624       1 wrap.go:32] apiserver panic'd on GET /apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/01-ubuntu1404/console```

```
E0920 12:51:13.717486       1 runtime.go:73] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
goroutine 6564791 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3a432e0, 0xc00038fd90)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc002319c60, 0x1, 0x1)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x3a432e0, 0xc00038fd90)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc009bf7440, 0xc00cabee60)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:238 +0x1a9
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc0072e2220, 0x73a86e0, 0xc00ef25a40, 0xc016ce7c00)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:122 +0x2ab
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x73a86e0, 0xc00ef25a40, 0xc016ce7b00)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xf3
net/http.HandlerFunc.ServeHTTP(0xc00430fcb0, 0x73a86e0, 0xc00ef25a40, 0xc016ce7b00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x73a86e0, 0xc00ef25a40, 0xc016ce7a00)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x2b8
net/http.HandlerFunc.ServeHTTP(0xc00430fce0, 0x73a86e0, 0xc00ef25a40, 0xc016ce7a00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x73a86e0, 0xc00ef25a40, 0xc016ce7a00)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x127
net/http.HandlerFunc.ServeHTTP(0xc0072e2240, 0x73a9c20, 0xc009ad9ce0, 0xc016ce7a00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00430fd10, 0x73a9c20, 0xc009ad9ce0, 0xc016ce7a00)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0079321a0, 0x73a9c20, 0xc009ad9ce0, 0xc016ce7a00)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00cabedc0, 0x73b3560, 0xc00b9fd440)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4
I0920 12:51:13.717593       1 log.go:172] http: response.WriteHeader on hijacked connection from k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader (httplog.go:184)
I0920 12:51:13.717617       1 log.go:172] http: response.Write on hijacked connection from k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).Write (httplog.go:168)
E0920 12:51:13.717624       1 wrap.go:32] apiserver panic'd on GET /apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/01-ubuntu1404/console
I0920 12:51:13.717704       1 log.go:172] http: panic serving 10.71.30.122:49636: killing connection/stream because serving request timed out and response had been started
goroutine 6564791 [running]:
net/http.(*conn).serve.func1(0xc00cabedc0)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x3a432e0, 0xc00038fd90)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc002319c60, 0x1, 0x1)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x3a432e0, 0xc00038fd90)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc009bf7440, 0xc00cabee60)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:238 +0x1a9
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc0072e2220, 0x73a86e0, 0xc00ef25a40, 0xc016ce7c00)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:122 +0x2ab
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x73a86e0, 0xc00ef25a40, 0xc016ce7b00)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xf3
net/http.HandlerFunc.ServeHTTP(0xc00430fcb0, 0x73a86e0, 0xc00ef25a40, 0xc016ce7b00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x73a86e0, 0xc00ef25a40, 0xc016ce7a00)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x2b8
net/http.HandlerFunc.ServeHTTP(0xc00430fce0, 0x73a86e0, 0xc00ef25a40, 0xc016ce7a00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x73a86e0, 0xc00ef25a40, 0xc016ce7a00)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x127
net/http.HandlerFunc.ServeHTTP(0xc0072e2240, 0x73a9c20, 0xc009ad9ce0, 0xc016ce7a00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00430fd10, 0x73a9c20, 0xc009ad9ce0, 0xc016ce7a00)
        /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0079321a0, 0x73a9c20, 0xc009ad9ce0, 0xc016ce7a00)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00cabedc0, 0x73b3560, 0xc00b9fd440)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4
I0920 13:41:23.566159       1 trace.go:81] Trace[2031942484]: "List etcd3: key=/jobs, resourceVersion=, limit: 500, continue: " (started: 2019-09-20 13:41:21.974868861 +0000 UTC m=+78375.159233816) (total time: 1.591251186s):
Trace[2031942484]: [1.591251186s] [1.591251186s] END
I0920 13:41:23.566183       1 trace.go:81] Trace[1163219066]: "Get /apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/ls-hw-0919b" (started: 2019-09-20 13:41:21.616265481 +0000 UTC m=+78374.800630420) (total time: 1.949
89314s):
Trace[1163219066]: [1.949830678s] [1.949795495s] About to write a response
I0920 13:41:23.566207       1 trace.go:81] Trace[689864830]: "Get /api/v1/namespaces/kubevirt/endpoints/virt-controller" (started: 2019-09-20 13:41:21.68801098 +0000 UTC m=+78374.872375934) (total time: 1.878175753s):
Trace[689864830]: [1.878104524s] [1.878092576s] About to write a response
I0920 13:41:23.566245       1 trace.go:81] Trace[600384476]: "List /apis/batch/v1/jobs" (started: 2019-09-20 13:41:21.974809373 +0000 UTC m=+78375.159174328) (total time: 1.591420563s):
Trace[600384476]: [1.591368285s] [1.591316136s] Listing from storage done
I0920 13:41:23.566253       1 trace.go:81] Trace[1344965722]: "Get /api/v1/namespaces/default/persistentvolumeclaims/01-ubuntu1404" (started: 2019-09-20 13:41:23.053015246 +0000 UTC m=+78376.237380271) (total time: 513.215125ms):
Trace[1344965722]: [513.166848ms] [513.156107ms] About to write a response
I0920 13:41:23.566293       1 trace.go:81] Trace[493910913]: "Get /api/v1/namespaces/kube-system/endpoints/kube-scheduler" (started: 2019-09-20 13:41:21.561136478 +0000 UTC m=+78374.745501420) (total time: 2.005128049s):
Trace[493910913]: [2.005081895s] [2.005040069s] About to write a response
I0920 13:41:23.566387       1 trace.go:81] Trace[83468931]: "Get /api/v1/namespaces/kube-system/endpoints/kube-controller-manager" (started: 2019-09-20 13:41:22.549845481 +0000 UTC m=+78375.734210480) (total time: 1.016521529s):
Trace[83468931]: [1.016493183s] [1.016464531s] About to write a response
I0920 13:41:23.566456       1 trace.go:81] Trace[601077995]: "Get /api/v1/namespaces/cdi/configmaps/cdi-controller-leader-election-helper" (started: 2019-09-20 13:41:21.858989085 +0000 UTC m=+78375.043354039) (total time: 1.707447989s):
Trace[601077995]: [1.707385658s] [1.707375347s] About to write a response
I0920 13:41:23.566748       1 trace.go:81] Trace[456936654]: "Get /api/v1/nodes/ls-hw-0919b" (started: 2019-09-20 13:41:22.794002695 +0000 UTC m=+78375.978367635) (total time: 772.727672ms):
Trace[456936654]: [772.486051ms] [772.4746ms] About to write a response
I0920 13:41:55.137430       1 trace.go:81] Trace[2047947746]: "Get /api/v1/namespaces/cdi/configmaps/cdi-operator-leader-election-helper" (started: 2019-09-20 13:41:54.165301464 +0000 UTC m=+78407.349666420) (total time: 972.098711ms):
Trace[2047947746]: [972.025624ms] [972.012477ms] About to write a response
I0920 13:41:55.137430       1 trace.go:81] Trace[188208368]: "Get /api/v1/namespaces/kubevirt/endpoints/virt-controller" (started: 2019-09-20 13:41:54.35854462 +0000 UTC m=+78407.542909561) (total time: 778.855284ms):
Trace[188208368]: [778.797942ms] [778.771965ms] About to write a response
I0920 13:41:55.137485       1 trace.go:81] Trace[996309513]: "Get /api/v1/namespaces/cdi/configmaps/cdi-controller-leader-election-helper" (started: 2019-09-20 13:41:54.391334224 +0000 UTC m=+78407.575699306) (total time: 746.113691ms):
Trace[996309513]: [746.024378ms] [746.012426ms] About to write a response
I0920 13:41:55.137430       1 trace.go:81] Trace[516674197]: "Get /api/v1/namespaces/kubevirt/endpoints/virt-operator" (started: 2019-09-20 13:41:53.890944179 +0000 UTC m=+78407.075309123) (total time: 1.246455266s):
Trace[516674197]: [1.246410004s] [1.246402075s] About to write a response
I0920 13:41:57.159547       1 trace.go:81] Trace[1141048676]: "Get /api/v1/namespaces/kubevirt/endpoints/virt-controller" (started: 2019-09-20 13:41:56.315627336 +0000 UTC m=+78409.499992276) (total time: 843.891401ms):
Trace[1141048676]: [843.829542ms] [843.813801ms] About to write a response
```
After that I can see lots of connection errors:

```
E0920 13:51:44.375164       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Service: Get https://[::1]:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: cannot assign requested address
E0920 13:51:44.376313       1 reflector.go:125] k8s.io/kube-aggregator/pkg/client/informers/internalversion/factory.go:117: Failed to list *apiregistration.APIService: Get https://[::1]:6443/apis/apiregistration.k8s.io/v1/apiservices?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: cannot assign requested address
E0920 13:51:44.377435       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Endpoints: Get https://[::1]:6443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: cannot assign requested address
E0920 13:51:44.378624       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Namespace: Get https://[::1]:6443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: cannot assign requested address
E0920 13:51:44.379816       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.RoleBinding: Get https://[::1]:6443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: cannot assign requested address
E0920 13:51:44.380858       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Role: Get https://[::1]:6443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: cannot assign requested address
E0920 13:51:44.381938       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.LimitRange: Get https://[::1]:6443/api/v1/limitranges?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: cannot assign requested address
```
I fact I'm able to list k8s resources like pods, deployments, configmaps but can't create new resources:

```
root@LS-HW-0919B:~/sriov-network-device-plugin# kubectl create -f images/configMap.yaml
Error from server: error when creating "images/configMap.yaml": Get https://[::1]:6443/api/v1/namespaces/kube-system/resourcequotas: dial tcp [::1]:6443: connect: cannot assign requested address
```

**What you expected to happen**:

kube apiserver fully operational

**How to reproduce it (as minimally and precisely as possible)**:

unsure

**Anything else we need to know?**:

I'm using Multus, Flannel and OVS CNI

**Environment**:
- KubeVirt version (use `virtctl version`):

```
Client Version: version.Info{GitVersion:"v0.20.6", GitCommit:"0ca091bb179c87f605111494f2e7e7d54fcd2c41", GitTreeState:"clean", BuildDate:"2019-09-10T11:07:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.17.0", GitCommit:"a067696ed6c25b0eab9dfcd01bbdc045f500f8ca", GitTreeState:"clean", BuildDate:"2019-05-06T14:58:11Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: 01-ubuntu1404
  labels:
    provider: 01-ubuntu1404
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: pvcdisk
      interfaces:
        - name: ovs-net
          bridge: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 2048M
  networks:
  - name: ovs-net
    multus: # Secondary multus network
      networkName: ovs-net1
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: 01-ubuntu1404
```

- Cloud provider or hardware configuration:

On premise installation, two physical boxes with Ubuntu 18.04 OS installed. 1 master + 1 worker

- OS (e.g. from /etc/os-release):

18.04.3 LTS (Bionic Beaver)

- Kernel (e.g. `uname -a`):

4.15.0-62

- Install tools:

K8s cluster bootstrapped with kubeadm

- Others:

**Comment by petrkotas** [comment]
@brysk what is the config map yuu tried to create? I see multus and sriov in your descriptions. Did you install the required plugins for them? Adding @phoracek as he is more familiar with the networking.

**Comment by brysk** [comment]
Hi @petrkotas 

Yes, there's also sriov network plugin in play. I was actually in the middle of sriov plugin deployment here: https://github.com/intel/sriov-network-device-plugin#example-deployments and you can find the configMap in this location: https://github.com/intel/sriov-network-device-plugin/blob/master/images/configMap.yaml


> Did you install the required plugins for them?
Yes, Multus, OVS and Flannel have been installed. Also sriov binary was already there.

I wasn't able to create anything so it's not just this configmap.

**Comment by petrkotas** [comment]
This sounds strange, can you please share the state of the cluster?
`kubectl get pods --all-namespaces` and share logs for any failures?

**Comment by brysk** [comment]
I had to delete kube-apiserver pod to bring it back to operational state. (it was recreated by kubelet) I'm now running some VMs with 2 interfaces, one provided by OVS CNI and second by SRIOV and waiting for reoccurrence. 

In the meantime I can share apiserver and controller logs.


```
root@LS-HW-0919B:~/k8s/ubuntu1604# kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY   STATUS    RESTARTS   AGE
cdi           cdi-apiserver-6f9f47d448-qlpr6          1/1     Running   0          2d17h
cdi           cdi-deployment-685df4b75c-pqbcr         1/1     Running   0          2d17h
cdi           cdi-operator-858fbd8bbd-9c6pl           1/1     Running   0          2d17h
cdi           cdi-uploadproxy-79697654f8-l2k8b        1/1     Running   0          2d17h
default       hostpath-provisioner-575b95c95c-7m2bp   1/1     Running   0          2d17h
default       virt-launcher-01-ubuntu1404-tkhrg       1/1     Running   0          61m
default       virt-launcher-01-ubuntu1604-bmvls       1/1     Running   0          34m
kube-system   coredns-5c98db65d4-bx9pn                1/1     Running   3          4d
kube-system   coredns-5c98db65d4-xjknx                1/1     Running   6          6d1h
kube-system   etcd-ls-hw-0919b                        1/1     Running   15         6d1h
kube-system   kube-apiserver-ls-hw-0919b              1/1     Running   17         3d
kube-system   kube-controller-manager-ls-hw-0919b     1/1     Running   6          6d1h
kube-system   kube-flannel-ds-amd64-67rxc             1/1     Running   1          6d1h
kube-system   kube-flannel-ds-amd64-chhw4             1/1     Running   24         6d1h
kube-system   kube-multus-ds-amd64-bkc8c              1/1     Running   1          6d1h
kube-system   kube-multus-ds-amd64-zh4nk              1/1     Running   5          6d1h
kube-system   kube-proxy-lzr6q                        1/1     Running   1          6d1h
kube-system   kube-proxy-vnncw                        1/1     Running   5          6d1h
kube-system   kube-scheduler-ls-hw-0919b              1/1     Running   6          6d1h
kube-system   kube-sriov-device-plugin-amd64-7ghlt    1/1     Running   0          3d
kube-system   kube-sriov-device-plugin-amd64-zlrgc    1/1     Running   0          3d
kube-system   ovs-cni-amd64-528pj                     2/2     Running   10         5d5h
kube-system   ovs-cni-amd64-9zglh                     2/2     Running   2          5d5h
kubevirt      virt-api-dd9dcb88d-dm78t                1/1     Running   0          63m
kubevirt      virt-api-dd9dcb88d-slbhm                1/1     Running   0          63m
kubevirt      virt-controller-55665799d6-gjbgp        1/1     Running   0          63m
kubevirt      virt-controller-55665799d6-xh6sm        1/1     Running   0          62m
kubevirt      virt-handler-f7kk2                      1/1     Running   0          62m
kubevirt      virt-operator-79dbb5747d-22882          1/1     Running   0          62m
kubevirt      virt-operator-79dbb5747d-s2ghf          1/1     Running   0          63m
```

[kube-logs.tar.gz](https://github.com/kubevirt/kubevirt/files/3642788/kube-logs.tar.gz)

**Comment by phoracek** [comment]
Hello @brysk, makes me happy to see OVS and SR-IOV being used/tested!

I would recommend you to install SR-IOV plugin via OpenShift's SR-IOV operator. We test it on Kubernetes, so it should work just fine. It does all the heavy lifting for you. If you hit an issue with the operator, please let us know. @booxter and @fedepaol are working closely with the operator's team.

https://github.com/openshift/sriov-network-operator

**Comment by SchSeba** [comment]
@brysk which version of k8s are you using?

looks like our console stream kills the k8s api pod this is really weird.

**Comment by brysk** [comment]
@SchSeba it's 1.15, you can check version details in the first post

**Comment by rmohr** [comment]
So fare we only test against 1.15.1. Might be a regression in k8s 1.15.3.

**Comment by slintes** [comment]
You are running different versions of KubeVirt and virtctl. Can you try virtctl v0.17.0? There have been some changes for console / vnc connections (even though I am not sure without having a deeper look if virtctl itself was affected by this, however it is always better to use mat hing version)

**Comment by brysk** [comment]
@slintes I will try v0.17.0. In fact I haven't seen any recurrence so far
