### ISSUE TITLE
testvm crash loops

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt#3381]
/kind bug

**What happened**:
I deployed minikube and ran through the "Use KubeVirt" lab.  The testvm crash loops.

**What you expected to happen**:
I expect a running and stable virtual machine

**How to reproduce it (as minimally and precisely as possible)**:
Install Fedora 32
Host preparations...
* setenforce Permissive
* install libvirtd
* set sock_rw group and sock_group mod
* create user and add to libvirt group
* install cri-o
* set k8s.conf kernel parameters
* modprobe br_netfilter
* yum install -y kubelet kubeadm kubectl
* Start minikube ... `minikube start --driver=none --container-runtime=cri-o`

**Anything else we need to know?**:
```
# kubectl get vmis
NAME     AGE   PHASE        IP    NODENAME
testvm   9s    Scheduling
# kubectl get vmis
NAME     AGE   PHASE       IP           NODENAME
testvm   10s   Scheduled   10.85.0.78   cube0
# kubectl get vmis
NAME     AGE   PHASE   IP    NODENAME
testvm   0s
#
```
```
# kubectl describe vmis/testvm
....
Status:
  Active Pods:
    eb32b3ad-2f01-4fbc-a2f4-badc4b7a4a43:  cube0
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               cannot migrate VMI which does not use masquerade to connect to the pod network
    Reason:                InterfaceNotLiveMigratable
    Status:                False
    Type:                  LiveMigratable
    Last Probe Time:       <nil>
    Last Transition Time:  2020-05-06T20:59:57Z
    Message:               failed to detect VMI pod: dial unix //pods/eb32b3ad-2f01-4fbc-a2f4-badc4b7a4a43/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused
    Reason:                Synchronizing with the Domain failed.
    Status:                False
    Type:                  Synchronized
  Guest OS Info:
  Interfaces:
    Ip Address:      10.85.0.91
    Name:            default
  Migration Method:  BlockMigration
  Node Name:         cube0
  Phase:             Scheduled
  Qos Class:         Burstable
Events:
  Type     Reason            Age               From                       Message
  ----     ------            ----              ----                       -------
  Normal   SuccessfulCreate  10s               virtualmachine-controller  Created virtual machine pod virt-launcher-testvm-986sn
  Warning  SyncFailed        2s                virt-handler, cube0        unknown error encountered sending command SyncVMI: rpc error: code = Unavailable desc = transport is closing
  Warning  SyncFailed        1s (x14 over 2s)  virt-handler, cube0        failed to detect VMI pod: dial unix //pods/eb32b3ad-2f01-4fbc-a2f4-badc4b7a4a43/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused
[root@cube0 ~]#
```

**Environment**:
- KubeVirt version (use `virtctl version`):
```
# ./virtctl version
Client Version: version.Info{GitVersion:"v0.29.0", GitCommit:"cbb7eaddb34d38da15868b19d84647f668a6134b", GitTreeState:"clean", BuildDate:"2020-05-05T03:33:18Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml
- Cloud provider or hardware configuration: BareMetal
- OS (e.g. from /etc/os-release): Fedora 32
- Kernel (e.g. `uname -a`): 
```
# uname -a
Linux cube0 5.6.8-300.fc32.x86_64 #1 SMP Wed Apr 29 19:01:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/redhat-release
Fedora release 32 (Thirty Two)
```
- Install tools:

- Others:

**Comment by rmohr** [comment]
@davidvossel might be related to the recent socket change.

**Comment by davidvossel** [comment]
very interesting. Yes, I'm going to take a look at trying to reproduce this myself.

**Comment by davidvossel** [comment]
@mazzystr 

Looking at your setup you're using `--driver=none` for minikube, which means you're setting up the environment yourself. It's going to be difficult to track down what's going on here if you're manually setting up the node in a custom way.

I attempted something similar to what you have by using the same k8s v1.18.2 release, but used the kvm driver instead

```
minikube config -p kubevirt set memory 6096
minikube config -p kubevirt set vm-driver kvm2
minikube config -p kubevirt set disk-size 270g
minikube start -p kubevirt
```

I didn't have any issues starting a vmi with the cirros containerDisk image in this setup.

In your minikube vm, can you see if the kubelet is configured to use the standard `/var/lib/kubelet/pods` directory, and if so what ownership/permissions that directory has?

thanks

**Comment by mazzystr** [comment]
I'm using minikube to deploy k8s on my baremetal which is a HP EliteDesk Mini G2 (Intel Core i5 with 8 gb memory.  I'm not fond of nested virtualization.  I simply do a Fedora 32 standard server install.  My host preparations are listed in the bug report.  There's very little customization.

```
[root@cube0 log]# ls -ld /var/lib/kubelet/pods
drwxr-x---. 18 root root 4096 May  8 13:05 /var/lib/kubelet/pods
[root@cube0 log]# ls -la /var/lib/kubelet/pods/
total 4
drwxr-x---. 18 root root 4096 May  8 13:05 .
drwx------.  8 root root  180 May  8 08:40 ..
drwxr-x---.  5 root root   71 May  8 08:41 053ea462-5074-40cb-ad27-7e075b80990d
drwxr-x---.  5 root root   71 May  8 08:40 0afaa17acd611ee886a9c8b35b71891d
drwxr-x---.  5 root root   71 May  8 08:58 18c2cd0d-37c3-45e9-ba54-d5b912206532
drwxr-x---.  5 root root   71 May  8 08:58 1f3cdf27-2c43-4e6f-b90b-3560909ea0f7
drwxr-x---.  5 root root   71 May  8 09:04 1f4549ae-82e0-4d14-aac4-5bc3688ed33b
drwxr-x---.  5 root root   71 May  8 09:04 24936315-510e-428e-9c54-c54c67df1305
drwxr-x---.  5 root root   71 May  8 08:40 28eecbd5-c8b0-4122-9325-989b3882c384
drwxr-x---.  5 root root   71 May  8 08:40 5795d0c442cb997ff93c49feeb9f6386
drwxr-x---.  5 root root   71 May  8 08:40 6cb530a5-38d3-4739-adde-68e3c7ea4214
drwxr-x---.  5 root root   71 May  8 08:40 6cd24352540c39a8d6334fa298f47c74
drwxr-x---.  5 root root   71 May  8 13:05 74a8a3de-e1d9-423f-b474-71bb11539f76
drwxr-x---.  5 root root   71 May  8 08:41 77390868-3cec-40d1-b41b-677df072c290
drwxr-x---.  5 root root   71 May  8 09:04 80ab0189-5485-4dcb-842a-eb08a860be20
drwxr-x---.  5 root root   71 May  8 08:40 88e6c47ce14900c76f81269925696e01
drwxr-x---.  5 root root   71 May  8 09:04 c6d15e9f-4b3d-471e-8ea3-942155de5fad
drwxr-x---.  5 root root   71 May  8 09:04 f62fba28-753e-4a41-8cca-0f8112557a62
```

I'm happy to chat over in kubernetes slack

**Comment by davidvossel** [comment]
@mazzystr can you provide logs for both virt-launcher and virt-handler

For virt-launcher, we need logs for the compute container. so `kubectl logs <pod name> -c compute`

thanks!

**Comment by mazzystr** [comment]
```
[root@cube0 ~]# kubectl logs `kubectl get pods | grep -v NAME | awk {'print $1'}` -c compute -f
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:68","timestamp":"2020-05-11T22:40:22.674203Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:71","timestamp":"2020-05-11T22:40:22.674370Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu:///system","pos":"libvirt.go:356","timestamp":"2020-05-11T22:40:22.721660Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:364","timestamp":"2020-05-11T22:40:22.721906Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 5.6.0, package: 7.fc31 (Unknown, 2019-11-22-21:16:59, )","subcomponent":"libvirt","thread":"42","timestamp":"2020-05-11T22:40:22.737000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvm","subcomponent":"libvirt","thread":"42","timestamp":"2020-05-11T22:40:22.737000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory","pos":"virDBusGetSystemBus:108","subcomponent":"libvirt","thread":"42","timestamp":"2020-05-11T22:40:22.737000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (/usr/sbin/dmidecode -q -t 0,1,2,3,4,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2792","subcomponent":"libvirt","thread":"42","timestamp":"2020-05-11T22:40:22.739000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:372","timestamp":"2020-05-11T22:40:23.223096Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:372","timestamp":"2020-05-11T22:40:23.224520Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:72","timestamp":"2020-05-11T22:40:23.224654Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"testvm","namespace":"default","pos":"manager.go:922","timestamp":"2020-05-11T22:40:27.106542Z","uid":"de8e2cc4-fd5a-4031-8244-3e79ea664a5e"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"testvm","namespace":"default","pos":"manager.go:941","timestamp":"2020-05-11T22:40:27.106597Z","uid":"de8e2cc4-fd5a-4031-8244-3e79ea664a5e"}
{"component":"virt-launcher","kind":"","level":"info","msg":"bridge pod interface: VIF: { Name: eth0, IP: 10.85.0.25, Mask: ffff0000, MAC: 2e:ce:1c:6d:06:7b, Gateway: 10.85.0.1, MTU: 1500, IPAMDisabled: false} \u0026{vmi:0xc00190c000 vif:0xc000146900 iface:0xc00029a5a0 virtIface:0xc000578840 podNicLink:\u003cnil\u003e domain:0xc0000fa000 podInterfaceName:eth0 bridgeInterfaceName:k6t-eth0}","name":"testvm","namespace":"default","pos":"podinterface.go:317","timestamp":"2020-05-11T22:40:27.107042Z","uid":"de8e2cc4-fd5a-4031-8244-3e79ea664a5e"}
{"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \n`\u0000\n","pos":"converter.go:1548","timestamp":"2020-05-11T22:40:27.107163Z"}
{"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf: default.svc.cluster.local svc.cluster.local cluster.local","pos":"converter.go:1549","timestamp":"2020-05-11T22:40:27.107180Z"}
{"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"dhcp.go:64","timestamp":"2020-05-11T22:40:27.107213Z"}
{"component":"virt-launcher","level":"error","msg":"failed to run DHCP: operation not permitted","pos":"common.go:315","timestamp":"2020-05-11T22:40:27.107444Z"}
panic: operation not permitted

goroutine 45 [running]:
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/network.(*NetworkUtilsHandler).StartDHCP.func1(0xc000146900, 0xc0008243d8, 0x8, 0xc00058ed20, 0xc0003a3c20, 0x1, 0x1, 0xc0004a8b00, 0x3, 0x4, ...)
	pkg/virt-launcher/virtwrap/network/common.go:316 +0x372
created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/network.(*NetworkUtilsHandler).StartDHCP
	pkg/virt-launcher/virtwrap/network/common.go:301 +0x35f
```

**Comment by davidvossel** [comment]
`{"component":"virt-launcher","level":"error","msg":"failed to run DHCP: operation not permitted","pos":"common.go:315","timestamp":"2020-05-11T22:40:27.107444Z"}`

Oh, I bet this has to do with the NET_RAW capability needing to be added to virt-launcher. We just added that but it didn't make it into the v0.29 release.

https://github.com/kubevirt/kubevirt/pull/3338

Can you try out master by chance and see if this is resolved?

**Comment by mazzystr** [comment]
Is there a master build or do I have to build myself?

**Comment by mazzystr** [comment]
This no longer seems to be an issue in Fedora 32...
```
$ kubectl get all
NAME                             READY   STATUS    RESTARTS   AGE
pod/virt-launcher-testvm-vw8sl   1/1     Running   0          49m

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   4d22h

NAME                               AGE
cdiconfig.cdi.kubevirt.io/config   4d22h

NAME                      AGE     PHASE
cdi.cdi.kubevirt.io/cdi   4d22h   Deployed

NAME                                        AGE   PHASE     IP             NODENAME
virtualmachineinstance.kubevirt.io/testvm   49m   Running   10.1.0.62/16   minikube

NAME                                AGE     RUNNING   VOLUME
virtualmachine.kubevirt.io/testvm   4d21h   true
```

**Comment by mazzystr** [comment]
This is no longer an issue

/close
