### ISSUE TITLE
Errors during LiveMigration with shared Volume

### ISSUE THREAD

**Issue by harutyundermenjyan** [kubevirt/kubevirt#3453]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Error during LiveMigration:
Bellow the last few lines of the failed pod.
```
{"component":"virt-launcher","kind":"","level":"info","msg":"Prepared migration target pod","name":"vm1","namespace":"default","pos":"server.go:148","timestamp":"2020-05-20T14:29:39.460627Z","uid":"c72b2e38-21c9-4f97-8c46-ad2d404326e2"}
panic: timed out waiting for domain to be defined

goroutine 1 [running]:
main.waitForDomainUUID(0x45d964b800, 0xc0000df6e0, 0xc0000f79e0, 0x1a4a480, 0xc000128550, 0xc0000df6e0)
	cmd/virt-launcher/virt-launcher.go:242 +0x41a
main.main()
	cmd/virt-launcher/virt-launcher.go:453 +0x10ed
{"component":"virt-launcher","level":"error","msg":"dirty virt-launcher shutdown","pos":"virt-launcher.go:535","reason":"exit status 2","timestamp":"2020-05-20T14:34:34.686347Z"}
```
**What you expected to happen**:
Expected to LiveMigrate and change the state of the old VMI pod completed.

**How to reproduce it (as minimally and precisely as possible)**:
created StorageClass, Shared Volume, and the VM/VMI with that shared Volume, then tried to `virtctl migrate vm1`

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): `v0.28.0`
- Kubernetes version (use `kubectl version`): `client v1.17.0`, `server v1.17.4`
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu18.04 lts and ubuntu16.04 lts
- Kernel (e.g. `uname -a`): `4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by vladikr** [comment]
According to this log, it shows that the migration didn't start and the destination virt-launcher has just terminated after a timeout.
In order to see why the migration didn't start we will need to see the logs from the source virt-launcher and the source virt-handler.

I'm wondering if you could reproduce this and post these logs?

**Comment by harutyundermenjyan** [comment]
After looking at the corresponding virt-launcher log noticed that there were some problems with nfs-provisioner, after solving the nfs-provisioner issue the LiveMigration succeeded but only with `Migration Method: LiveMigration`. Is it OK if it failed with method `BlockMigration` in case of shared volume?
Thank you for help and pointing to the right logs.

**Comment by vladikr** [comment]
It's great to hear that migration is working for you.
Yes, absolutely. The `BlockMigration` is needed to migrate VMs with non-shared block volumes (not filesystem volumes such as NFS), however, currently, it's working only with disks such as the container disk.

**Comment by harutyundermenjyan** [comment]
Tried to run the LiveMigration second time with method `LiveMigration` to make sure it works properly but this time I got the same error I've shared above.
Here are the last few lines from the virt-launcher container:
```
{"component":"virt-handler","level":"info","msg":"failed to dial cmd socket: /var/run/kubevirt/sockets/4979051e-0039-4cec-b0dd-e4f416c96bd2_sock","pos":"client.go:137","reason":"context deadline exceeded","timestamp":"2020-05-21T18:08:38.818711Z"}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vm1","namespace":"default","pos":"vm.go:995","reason":"context deadline exceeded","timestamp":"2020-05-21T18:08:38.818872Z","uid":"4979051e-0039-4cec-b0dd-e4f416c96bd2"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/vm1","pos":"vm.go:647","reason":"context deadline exceeded","timestamp":"2020-05-21T18:08:38.818941Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T18:10:00.739177Z"}
{"component":"virt-handler","level":"info","msg":"VMI does not exist","pos":"vm.go:864","timestamp":"2020-05-21T18:10:00.739317Z"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Paused, reason: StartingUp\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T18:10:00.739397Z","uid":""}
{"component":"virt-handler","level":"info","msg":"failed to dial cmd socket: /var/run/kubevirt/sockets/4979051e-0039-4cec-b0dd-e4f416c96bd2_sock","pos":"client.go:137","reason":"context deadline exceeded","timestamp":"2020-05-21T18:10:02.739689Z"}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vm1","namespace":"default","pos":"vm.go:995","reason":"context deadline exceeded","timestamp":"2020-05-21T18:10:02.739827Z","uid":"4979051e-0039-4cec-b0dd-e4f416c96bd2"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/vm1","pos":"vm.go:647","reason":"context deadline exceeded","timestamp":"2020-05-21T18:10:02.739891Z"}
```

**Comment by harutyundermenjyan** [comment]
Also got this for every 15 second:
```
{"component":"virt-handler","kind":"Domain","level":"warning","msg":"detected expired watchdog for domain","name":"vm1","namespace":"default","pos":"cache.go:114","timestamp":"2020-05-21T18:54:15.231692Z","uid":""}
```

**Comment by harutyundermenjyan** [comment]
And here are some logs from another attempt:
**virt-launcher logs where the VMI is currently running:**
```
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:19.675460Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:19.675577Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:19.675650Z","uid":""}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:20.127106Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:20.127235Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:20.127293Z","uid":""}
{"component":"virt-handler","level":"info","msg":"Proxy Source listening on unix file /var/run/kubevirt/migrationproxy/2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f-source.sock for key 2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f","pos":"migration-proxy.go:264","timestamp":"2020-05-21T19:27:20.245385Z"}
{"component":"virt-handler","level":"info","msg":"Proxy Source listening on unix file /var/run/kubevirt/migrationproxy/2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f-49152-source.sock for key 2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f","pos":"migration-proxy.go:264","timestamp":"2020-05-21T19:27:20.245538Z"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Received Domain Event of type MODIFIED","name":"vm1","namespace":"default","pos":"server.go:77","timestamp":"2020-05-21T19:27:20.296634Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:20.296868Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:20.296933Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:20.296976Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:20.760747Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:20.760836Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:20.760875Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"warning","msg":"detected expired watchdog for domain","name":"u16","namespace":"default","pos":"cache.go:114","timestamp":"2020-05-21T19:27:20.978237Z","uid":""}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:21.879197Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:21.879312Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:21.879359Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"info","msg":"692 bytes read from oubound connection","pos":"migration-proxy.go:390","timestamp":"2020-05-21T19:27:22.062120Z"}
{"component":"virt-handler","level":"info","msg":"6748 bytes written oubound connection","pos":"migration-proxy.go:397","timestamp":"2020-05-21T19:27:22.062271Z"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Received Domain Event of type MODIFIED","name":"vm1","namespace":"default","pos":"server.go:77","timestamp":"2020-05-21T19:27:22.341260Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:22.341519Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:22.341615Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:22.341665Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vm1","namespace":"default","pos":"vm.go:995","reason":"server error. command Migrate failed: \"migration job already executed\"","timestamp":"2020-05-21T19:27:22.465127Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/vm1","pos":"vm.go:647","reason":"server error. command Migrate failed: \"migration job already executed\"","timestamp":"2020-05-21T19:27:22.587297Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:22.587755Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:22.587832Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:22.587902Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"error","msg":"proxy unix socket listener returned error.","pos":"migration-proxy.go:434","reason":"accept unix /var/run/kubevirt/migrationproxy/2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f-source.sock: use of closed network connection","timestamp":"2020-05-21T19:27:22.704002Z"}
{"component":"virt-handler","level":"error","msg":"proxy unix socket listener returned error.","pos":"migration-proxy.go:434","reason":"accept unix /var/run/kubevirt/migrationproxy/2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f-49152-source.sock: use of closed network connection","timestamp":"2020-05-21T19:27:22.704130Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Updating the VirtualMachineInstance status failed.","name":"vm1","namespace":"default","pos":"vm.go:1002","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"vm1\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2020-05-21T19:27:22.767993Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/vm1","pos":"vm.go:647","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"vm1\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2020-05-21T19:27:22.768081Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:22.768153Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:22.768215Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:22.768280Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:23.011116Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:23.011190Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:23.011234Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"","level":"error","msg":"Updating the VirtualMachineInstance status failed.","name":"vm1","namespace":"default","pos":"vm.go:1002","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"vm1\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2020-05-21T19:27:23.396907Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/vm1","pos":"vm.go:647","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"vm1\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2020-05-21T19:27:23.396999Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:23.397070Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:23.397108Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:23.397155Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm1","pos":"vm.go:860","timestamp":"2020-05-21T19:27:23.937940Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm1","namespace":"default","pos":"vm.go:862","timestamp":"2020-05-21T19:27:23.938010Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm1","namespace":"default","pos":"vm.go:867","timestamp":"2020-05-21T19:27:23.938057Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"Domain","level":"warning","msg":"detected expired watchdog for domain","name":"u16","namespace":"default","pos":"cache.go:114","timestamp":"2020-05-21T19:27:35.978443Z","uid":""}
```
**virt-launcher logs to where the VMI is going to be migrated:**
```
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Received Domain Event of type MODIFIED","name":"vm1","namespace":"default","pos":"server.go:77","timestamp":"2020-05-21T19:27:22.238949Z","uid":""}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain is in state Paused reason StartingUp","name":"vm1","namespace":"default","pos":"vm.go:1634","timestamp":"2020-05-21T19:27:22.239099Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"The target node received the migrated domain","name":"vm1","namespace":"default","pos":"vm.go:798","timestamp":"2020-05-21T19:27:22.356706Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"","level":"info","msg":"The target node received the migrated domain","name":"vm1","namespace":"default","pos":"vm.go:798","timestamp":"2020-05-21T19:27:22.595589Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","level":"info","msg":"692 bytes read from oubound connection","pos":"migration-proxy.go:390","timestamp":"2020-05-21T19:27:22.660873Z"}
{"component":"virt-handler","level":"info","msg":"6748 bytes written oubound connection","pos":"migration-proxy.go:397","timestamp":"2020-05-21T19:27:22.661012Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"The target node received the migrated domain","name":"vm1","namespace":"default","pos":"vm.go:798","timestamp":"2020-05-21T19:27:23.316151Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"","level":"info","msg":"The target node received the migrated domain","name":"vm1","namespace":"default","pos":"vm.go:798","timestamp":"2020-05-21T19:27:23.441013Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
{"component":"virt-handler","kind":"","level":"info","msg":"The target node received the migrated domain","name":"vm1","namespace":"default","pos":"vm.go:798","timestamp":"2020-05-21T19:27:23.741742Z","uid":"2b1f7886-3a2e-4cdf-b7db-89b2cbba8a9f"}
```

**Comment by harutyundermenjyan** [comment]
Also noticed that the migration never succeeded if some RAM stress test activated during the LiveMigration time, in particular:
`stress -m 1 --vm-bytes 30G` _or_ `stress -m 1 --vm-bytes 30G --vm-keep`
Let me mention that the test going on with 256G ram instances.

**Comment by harutyundermenjyan** [comment]
I've created another issue for the last mentioned problem. [#3504](https://github.com/kubevirt/kubevirt/issues/3504).
