### ISSUE TITLE
failed to upload new image with CDI [port-forward]

### ISSUE THREAD

**Issue by talcoh2x** [kubevirt/kubevirt#4032]
Hi, I need your help. is my first time with CDI
I'm trying to upload a new image (qcow2) from my local machine.
I tried a lot of things:
- I created  dv & pv & pvc and then try run folowing commad - ./virtctl image-upload --pvc-name=minio-pv-claim   --namespace default  --size=5Gi --image-path /home/tacohen_nfs/Centos74-clean.qcow2  --uploadproxy-url=https://127.0.0.1:18443 --insecure

- I created only dv and try to run follwing command - 
./virtctl image-upload dv centos74  --namespace default  --size=5Gi --image-path /home/tacohen_nfs/Centos74-clean.qcow2  --uploadproxy-url=https://127.0.0.1:18443 --insecure
'''
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: upload-datavolume
spec:
  source:
      upload: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
'''

can't figure out what's the simple way to upload a new disk image from my local machine.
please help.

Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  persistentvolumeclaim "upload-datavolume-scratch" not found
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "cdi-upload-upload-datavolume": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "cdi-upload-upload-datavolume": pod has unbound immediate PersistentVolumeClaims

**Comment by talcoh2x** [comment]
@vladikr  @awels

**Comment by talcoh2x** [comment]
if I create manually the PV + PV scratch and the PVC 
I get the following error 



/virtctl image-upload dv centos74  --namespace default   --size=5Gi --image-path /home/tacohen_nfs/Centos74-clean.qcow2  --uploadproxy-url=https://10.111.12.16:31001  --insecure  --no-create
panic: assignment to entry in nil map

goroutine 1 [running]:
kubevirt.io/kubevirt/pkg/virtctl/imageupload.ensurePVCSupportsUpload(0x7f0b25b34118, 0xc00038a500, 0xc0000bafc0, 0x7f0b25b34118, 0xc00038a500, 0x8)
        pkg/virtctl/imageupload/imageupload.go:506 +0xb0
kubevirt.io/kubevirt/pkg/virtctl/imageupload.(*command).run(0xc000245d40, 0xc0003e8a00, 0xc0003ee3c0, 0x2, 0xa, 0x0, 0x0)
        pkg/virtctl/imageupload/imageupload.go:234 +0xda4
kubevirt.io/kubevirt/pkg/virtctl/imageupload.NewImageUploadCommand.func1(0xc0003e8a00, 0xc0003ee3c0, 0x2, 0xa, 0x0, 0x0)
        pkg/virtctl/imageupload/imageupload.go:123 +0x6d
kubevirt.io/kubevirt/vendor/github.com/spf13/cobra.(*Command).execute(0xc0003e8a00, 0xc0003ee280, 0xa, 0xa, 0xc0003e8a00, 0xc0003ee280)
        vendor/github.com/spf13/cobra/command.go:826 +0x465
kubevirt.io/kubevirt/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003ce000, 0x0, 0xc00014a3d0, 0x0)
        vendor/github.com/spf13/cobra/command.go:914 +0x2fc
kubevirt.io/kubevirt/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:864
kubevirt.io/kubevirt/pkg/virtctl.Execute()
        pkg/virtctl/root.go:101 +0x48
main.main()
        cmd/virtctl/virtctl.go:31 +0x22

**Comment by awels** [comment]
So kubernetes uses several things to decide if it can bind a PV to a PVC.
* AccessMode (These have to match, so a RWX PVC will not bind to a RWO PV)
* VolumeMode (These have to match)
* Size (only PVs with capacity >= PVC request size are considered)
* StorageClass and provisioner The storage class name has to match on the PVC and PV, as well as the provisioner on the PV has to match the provisioner on the storage class.
