### ISSUE TITLE
ghost record not cleanup properly causes error to find the correct launcher client

### ISSUE THREAD

**Issue by fanzhangio** [kubevirt/kubevirt#7032]
**BUG REPORT**:

/kind bug

**What happened**:
We noticed an issue that VMI stuck in Scheduled and the launcher pod was Error:
```
NAMESPACE  NAME          AGE    PHASE       IP     NODENAME
ns01       vm-08         12h    Scheduled            node01


NAMESPACE  NAME                        READY STATUS RESTARTS AGE 
ns01      virt-launcher-vm-08-2pdj6      2/3   Error     0   12h
```
Looked into the stuck vmi, the pod went to Error because the compute container was terminated due to timeout failure of creating virt-launcher client connection when the entry already exists with differing UID

>{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vm-08","namespace":"ns01","pos":"vm.go:1359","reason":"unable to create virt-launcher client connection: can not add ghost record when entry already exists with differing UID","timestamp":"2021-12-08T09:23:02.504977Z","uid":"054e439b-4402-4a65-9dd1-70e4235762b3"}

```
Events:
  Type     Reason      Age                     From          Message
  ----     ------      ----                    ----          -------
  Warning  SyncFailed  4m30s (x4316 over 13h)  virt-handler  unable to create virt-launcher client connection: can not add ghost record when entry already exists with differing UID
```
>{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:72","timestamp":"2021-12-08T09:23:02.187469Z"}
panic: timed out waiting for domain to be defined
>
>goroutine 1 [running]:
>main.waitForDomainUUID(0x45d964b800, 0xc0003376e0, 0xc0005a68a0, 0x1af0838, 0xc000452180, 0x0)
	cmd/virt-launcher/virt-launcher.go:218 +0x517
main.main()
	cmd/virt-launcher/virt-launcher.go:449 +0x1265

This is an issue that virt-handler was using a wrong virt-launcher client to build connection. 
> {"component":"virt-handler","kind":"VirtualMachineInstance","level":"error","msg":"Updating the VirtualMachineInstance status failed.","name":"vm-08","namespace":"ns01","pos":"vm.go:1366","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"vm-08\": StorageError: invalid object, Code: 4, Key: /registry/kubevirt.io/virtualmachineinstances/ns01/vm-08, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 8667609c-15c6-44dd-bdc1-704ee0bdf40f, UID in object meta: 054e439b-4402-4a65-9dd1-70e4235762b3","timestamp":"2021-12-08T09:22:54.560475Z","uid":"8667609c-15c6-44dd-bdc1-704ee0bdf40f"} 

The error `can not add ghost record when entry already exists with differing UID` showed that the ghost record was not deleted properly. This issue was noticed when a pod was evicted from node which went NotReady for a period of time, and virt-handler did not properly handle VMI shutdown process and cleanup of local data.

**What you expected to happen**:
A rebooted VMI scheduled to the node where a prior vmi of the same name was terminated improperly can be Running

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
- KubeVirt version (use `virtctl version`): 0.35
- Kubernetes version (use `kubectl version`): 1.20
- VM or VMI specifications:
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release):
   ```
    NAME="CentOS Linux"
    VERSION="8 (Core)"
     ID="centos"
     ID_LIKE="rhel fedora"
     VERSION_ID="8"
     PLATFORM_ID="platform:el8"
     PRETTY_NAME="CentOS Linux 8 (Core)"
     ANSI_COLOR="0;31"
     CPE_NAME="cpe:/o:centos:centos:8"
     HOME_URL="https://www.centos.org/"
     BUG_REPORT_URL="https://bugs.centos.org/"
     CENTOS_MANTISBT_PROJECT="CentOS-8"
     CENTOS_MANTISBT_PROJECT_VERSION="8"
     REDHAT_SUPPORT_PRODUCT="centos"
   ```
- Kernel (e.g. `uname -a`):
   ```
   Linux gs-node.nvmetal.net 4.18.0-193.13.2.el8.1622008870.664c92a05.x86_64 #1 SMP Wed May 26 13:04:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
   ```
- Install tools:
- Others:

**Comment by fanzhangio** [comment]
Here is what I investigated this issue and some thoughts :

For each new created virt-launcher pod needs to provide a launcher-socket and register it into `/var/run/kubevirt-private/ghost-records/<vmi id>` path for caching. And every time virt-launcher restarted it will read all files in this path into its cache. The issue happens after virt-handler restarted.

However the virt-handler on  was not able to add such a ghost socket into cache for VMI vm-08 whose VMI id id **054e439b-4402-4a65-9dd1-70e4235762b3** , pod UID is _6edd9777-06bf-4e3e-b415-32db7f35b637_ . Even though the pod and socket are created on host 
```
[root@virt-handler-vxdzm]# ls -la /pods/6edd9777-06bf-4e3e-b415-32db7f35b637/volumes/kubernetes.io~empty-dir/sockets/launcher-sock
srwxr-xr-x 1 root qemu 0 Dec  8 09:23 /pods/6edd9777-06bf-4e3e-b415-32db7f35b637/volumes/kubernetes.io~empty-dir/sockets/launcher-sock
```
The only one ghost socket in cache, instead, belongs to another VMI whose VMI UID **8667609c-15c6-44dd-bdc1-704ee0bdf40f** , pod UID is _5ef5c2c4-37d0-47b9-b025-d9b99dc1504d_
```
[root@virt-handler-vxdzm]# ls /var/run/kubevirt-private/ghost-records/
8667609c-15c6-44dd-bdc1-704ee0bdf40f
[root@virt-handler-vxdzm]# cat /var/run/kubevirt-private/ghost-records/8667609c-15c6-44dd-bdc1-704ee0bdf40f
{"name":"ngn-igw-08","namespace":"ngn-igw","socketFile":"//pods/5ef5c2c4-37d0-47b9-b025-d9b99dc1504d/volumes/kubernetes.io~empty-dir/sockets/launcher-sock","uid":"8667609c-15c6-44dd-bdc1-704ee0bdf40f"}
```
This VMI UID **8667609c-15c6-44dd-bdc1-704ee0bdf40f** was an old VMI of the same name (vm-08) that virt-launcher created before restarted. This virt-handler on this node was terminated at `2021-12-08 01:15:34`, and restarted at `2021-12-08 01:20:46` , so all the old vmi was terminated by kubelet and removed from /var/lib/kubelet/pods path on this node.
```
    State:          Running
      Started:      Wed, 08 Dec 2021 01:20:46 -0800
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 08 Dec 2021 01:13:28 -0800
      Finished:     Wed, 08 Dec 2021 01:15:34 -0800
```
After virt-handler restarted, it initialized the ghost record cache by reading files in /var/run/kubevirt-private/ghost-records/<vmi id> However for unknown reason, virt-handler was not able to complete finishing cleanup ghost record, so the same socket was leftover.  It is /var/run/kubevirt-private/ghost-records/8667609c-15c6-44dd-bdc1-704ee0bdf40f . At this moment, the restarted virt-handler was not able to make a cleanup because it can not retrieve the launcher-client by this file. 

> {"component":"virt-handler","level":"error","msg":"Unable to mark vmi as unresponsive socket //pods/5ef5c2c4-37d0-47b9-b025-d9b99dc1504d/volumes/kubernetes.io~empty-dir/sockets/launcher-sock","pos":"cache.go:486","reason":"open /pods/5ef5c2c4-37d0-47b9-b025-d9b99dc1504d/volumes/kubernetes.io~empty-dir/sockets/launcher-unresponsive: no such file or directory","timestamp":"2021-12-09T16:20:04.556793Z"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain is marked for deletion","name":"vm-08","namespace":"ns01","pos":"vm.go:2277","timestamp":"2021-12-09T16:20:04.556819Z","uid":"8667609c-15c6-44dd-bdc1-704ee0bdf40f"}

So, virt-handler has a key **<namespace/vmi name>** (in this case, it is ns01/vm-08) maps to two ghost records : **8667609c-15c6-44dd-bdc1-704ee0bdf40f** and **054e439b-4402-4a65-9dd1-70e4235762b3**, which caused error of proceed to find the correct launcher client. And compute container of the vm-08 pod has a timeout panic.

**Comment by rthallisey** [comment]
How would you reproduce this issue? Would it be these two steps on repeat:
1) reboot a node with active VMIs
2) recreate VMIs with the same name on the same node

**Comment by davidvossel** [comment]
interesting bug.

The ghost records exist in order to guarantee that a VMI's local data is cleaned up when virt-handler re-initializes even if the VMI is deleted from etcd.

What you're hitting is that the ghost record for a VMI is sticking around even after a new VMI with the exact same name has been created. Looking at the code, we don't handle this situation at all, and the result is the new VMI will never get processed.

Here's my suggestion as a fix.

When virt-handler is executing on a VMI, add a check to determine if an old ghost record exists for the a VMI with the same name but has a different UID. If that condition exists, run the equavalent of this code in order to process the cleanup of the old ghost record. https://github.com/kubevirt/kubevirt/blob/bf73abb9ac945bc0798b88235db8f487be0d5d82/pkg/virt-handler/vm.go#L1745 

We're already doing this exact same thing to cleanup when we detect an old domain exists somehow, so extend that logic to handle when an old ghost record exists somehow.

**Comment by BugMosquito** [comment]
Has this bug been fixed ？

**Comment by rthallisey** [comment]
This was observed in 0.35.  I think it's fixed in 0.40 by https://github.com/kubevirt/kubevirt/pull/5194.  This can be closed.

/close

**Comment by m14815** [comment]
> This was observed in 0.35. I think it's fixed in 0.40 by #5194. This can be closed.
> 
> /close

I recently get similar error with kubevirt version 0.41.0, after I modify some spec of vm, such as size of memory, and restart the vm for spec changing, the vmi will stay with scheduled state, and it shows the same error, the ghost record was not cleaned properly, and new info clashes will old one.

**Comment by BugMosquito** [comment]
> clashes

I also repeated this error in version 0.41.0, but the virtual machine recovered itself after a period of time

**Comment by rthallisey** [comment]
/reopen

I closed the wrong bug.  https://github.com/kubevirt/kubevirt/issues/6685 is fixed by https://github.com/kubevirt/kubevirt/pull/5194 in release 0.40

**Comment by fanzhangio** [comment]
/reopen

This is a reproducible bug in production when namespace/name is reused while UID is new, particular in a case when virt-launcher pod was force-deleted ends up missing domain in virt-handler's cache. The ghost socket cleanup path was skipped.
To root fix this bug, we should make virt-handler ghost-record reconciliation UID-safe for same-name VMI recreation

**1. Make ghost-record access UID-aware**
Extend GhostRecordStore with an immutable record lookup and compare-and-delete operation:
- Get(namespace, name) (GhostRecord, bool)
- DeleteIfUID(namespace, name, expectedUID) error

DeleteIfUID must:
- Hold the store lock across comparison and mutation.
- Remove the checkpoint only when the stored UID equals expectedUID.
- Never remove a mapping belonging to a different UID.
- Return a typed UID-mismatch error.
- Treat an already-absent expected record as successful for idempotency.

`GhostRecordStore.Add` must retain its differing-UID rejection as the final safety net. Reconciliation should normally resolve the conflict before Add is reached.

**2. Reconcile ghost conflicts before launcher-client creation**

During every VMI sync, inspect the ghost record regardless of whether a Domain exists.

For current VMI UID B and ghost UID A:

- If A == B, continue through the existing path.
- If A != B and A's launcher socket is responsive, block B, emit an event, and requeue with rate limiting.
- If A != B and A is still within the existing initialization/liveness grace period, requeue without starting B.
- If A != B and A is definitively dead, perform complete cleanup for UID A, delete the ghost record with DeleteIfUID(A), and requeue B.
- If liveness cannot be determined, fail closed and retain A.

The reconciliation must execute when:

- An old Domain exists.
- The old Domain has disappeared but its ghost checkpoint remains.
- virt-handler has restarted and reconstructed the ghost record.
- A Domain deletion notification was missed.

**3. Make all delayed cleanup UID-safe**

Refactor cleanup so that an operation for UID A cannot delete UID B state:

- Change CloseLauncherClient to return and propagate errors.
- Delete launcher-client state by UID.
- Delete the ghost record using DeleteIfUID.
- Remove the cached Domain only if its UID still equals the cleanup UID.
- Preserve any Domain or ghost record that belongs to a newer UID.
- Keep ghost and command-socket removal as the final cleanup stage.

**4. Add periodic self-healing**

At startup and during the existing Domain resync:
- Enumerate persisted ghost records.
- Enqueue every ghost key for reconciliation.
- For a missing or expired socket, publish/reconstruct stale state instead of silently skipping it.
- Ensure orphan ghost records are eventually cleaned even when no replacement VMI is created.

**5. Add observability**

Add Kubernetes events:

- StaleVMIIncarnationDetected
- StaleVMIIncarnationCleaned
- VMIIncarnationConflict
- StaleVMIIncarnationCleanupFailed

Add a low-cardinality metric such as:
```go
    kubevirt_virt_handler_stale_vmi_reconciliations_total{
        result="cleaned|blocked|error"
    } 
```
Logs must include namespace, name, old UID, current UID, node, socket path, and chosen action.

**Comment by fanzhangio** [comment]
@alancaldelas can you pick up this fix ?

**Comment by fossedihelm** [comment]
@fanzhangio Maybe these could help here?
- https://github.com/kubevirt/kubevirt/pull/18988
- https://github.com/kubevirt/kubevirt/pull/18338
