### ISSUE TITLE
Nil pointer dereference panic on vmi-create-admitter.go when 

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/kubevirt#8421]
**What happened**:
vmi-create-admitter.go panics composing an error message when Spec.Configuration.EvictionStrategy is set with an unexpected value on the CR for virt-operator.

in virt-api logs:
```
2022-09-06T18:57:29.243345170Z {"component":"virt-api","level":"info","msg":"http: panic serving 10.128.0.1:38264: runtime error: invalid memory address or nil pointer dereference\ngoroutine 3597 [running]:\nnet/http.(*conn).serve.func1()\n\tGOROOT/src/net/http/server.go:1802 +0xb9\npanic({0x1d2dc60, 0x382a5e0})\n\tGOROOT/src/runtime/panic.go:1047 +0x266\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/admitters.validateLiveMigration(0xc0088685a0, 0xc006802798, 0x0)\n\tpkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go:779 +0x145\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/admitters.ValidateVirtualMachineInstanceSpec(0x1fd174e, 0xc006802798, 0x0)\n\tpkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go:208 +0x1d4b\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/admitters.(*VMICreateAdmitter).Admit(0xc0004b11c0, 0xc008779c50)\n\tpkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go:100 +0x10c\nkubevirt.io/kubevirt/pkg/util/webhooks/validating-webhooks.Serve({0x2507758, 0xc008716ee0}, 0xc008716f20, {0x24ccc60, 0xc0004b11c0})\n\tpkg/util/webhooks/validating-webhooks/validating-webhook.go:73 +0xc9\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook.ServeVMICreate(...)\n\tpkg/virt-api/webhooks/validating-webhook/validating-webhook.go:34\nkubevirt.io/kubevirt/pkg/virt-api.(*virtAPIApp).registerValidatingWebhooks.func1({0x2507758, 0xc008716ee0}, 0x0)\n\tpkg/virt-api/api.go:773 +0x7a\nnet/http.HandlerFunc.ServeHTTP(0x0, {0x2507758, 0xc008716ee0}, 0xc008716ee0)\n\tGOROOT/src/net/http/server.go:2047 +0x2f\nnet/http.(*ServeMux).ServeHTTP(0xc0086e379e, {0x2507758, 0xc008716ee0}, 0xc00846b600)\n\tGOROOT/src/net/http/server.go:2425 +0x149\nnet/http.serverHandler.ServeHTTP({0x24f8900}, {0x2507758, 0xc008716ee0}, 0xc00846b600)\n\tGOROOT/src/net/http/server.go:2879 +0x43b\nnet/http.(*conn).serve(0xc0069e2500, {0x250a218, 0xc00261af00})\n\tGOROOT/src/net/http/server.go:1930 +0xb08\ncreated by net/http.(*Server).Serve\n\tGOROOT/src/net/http/server.go:3034 +0x4e8\n","pos":"server.go:3160","timestamp":"2022-09-06T18:57:29.243292Z"}
```

**What you expected to happen**:
vmi-create-admitter.go should correctly report the error message without failing on `runtime error: invalid memory address or nil pointer dereference`

**How to reproduce it (as minimally and precisely as possible)**:
1. Set a bad string on Spec.Configuration.EvictionStrategy on the CR for virt-operator
2. try to create a VM

**Additional context**:
See: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2071#issuecomment-1238958335
for an example

**Environment**:
- KubeVirt version (use `virtctl version`): v0.57.0-rc.0
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
@tiraboschi Was this addressed? 

/reopen

**Comment by tiraboschi** [comment]
No, I don't think so

**Comment by sudo-NithishKarthik** [comment]
I would like to work on this issue
