### ISSUE TITLE
Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory

### ISSUE THREAD

**Issue by naveenrpp2017** [kubevirt/kubevirt#9681]
**What happened**:
I have installed the Kubevirt and tried to create a VMI with below yaml file.

metadata:
  name: testvmi-containerdisk
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
spec:
  domain:
    resources:
      requests:
        memory: 10Gi
        cpu: 20
    devices:
      disks:
      - name: containerdisk
        disk: {}
      - name: cloudinitdisk
        disk:
          bus: virtio
      - name: rootdisk
        disk:
          bus: virtio
      interfaces:
        - name: default
          masquerade: {}
  networks:
    - name: default
      pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: quay.io/containerdisks/ubuntu:22.04
        imagePullPolicy: IfNotPresent
    - cloudInitNoCloud:
       userData: |-
         #cloud-config
         chpasswd:
           expire: false
         password: password
         user: fedora
      name: cloudinitdisk
    - name: rootdisk
      hostDisk:
       capacity: 20Gi
       path: /tmp/data/disk.img
       type: DiskOrCreate

Error:
VMI is not creating, getting below error.

# kubectl logs virt-launcher-testvmi-containerdisk-rxf8b
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-04-27T08:35:36.652452Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-04-27T08:35:36.652511Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:496","timestamp":"2023-04-27T08:35:36.653332Z"}
{"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-04-27T08:35:36.653608Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:504","timestamp":"2023-04-27T08:35:36.653825Z"}
panic: fork/exec /usr/sbin/virtqemud: errno 0

goroutine 13 [running]:
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud.func1()
        pkg/virt-launcher/virtwrap/util/libvirt_helper.go:251 +0x4ce
created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud
        pkg/virt-launcher/virtwrap/util/libvirt_helper.go:218 +0x65
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:124","timestamp":"2023-04-27T08:35:36.658464Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:142","timestamp":"2023-04-27T08:35:36.658600Z"}

**What you expected to happen**:
VMI needs to be created

**Environment**:
- KubeVirt version (use `virtctl version`): **v0.59.0**
- Kubernetes version (use `kubectl version`): **1.23.3**
- OS (e.g. from /etc/os-release): **ubuntu22.04**
- Kernel (e.g. `uname -a`): **5.15.0-25-generic**

**Comment by vasiliy-ul** [comment]
Hi @naveenrpp2017, what is your container runtime? If it's docker, try switching to containerd. If you are running minikube, please refer to https://github.com/kubevirt/kubevirt/issues/9664#issuecomment-1525216211.

**Comment by kylinklee** [comment]
Hi, have you solve this problem?What u do to solve this?

**Comment by salimep** [comment]
Hi,

i face the same issue  with openshift 14 release

```bash

2024-11-29T15:18:45.223418792+00:00 stderr F {"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2024-11-29T15:18:45.223253Z"}
2024-11-29T15:18:45.229027350+00:00 stderr F {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:524","timestamp":"2024-11-29T15:18:45.228745Z"}
2024-11-29T15:18:45.234749466+00:00 stderr F {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:532","timestamp":"2024-11-29T15:18:45.233559Z"}
2024-11-29T15:18:45.315463269+00:00 stderr F {"component":"virt-launcher","level":"info","msg":"libvirt version: 9.0.0, package: 10.10.el9_2 (Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>, 2024-09-12-10:51:56, )","subcomponent":"libvirt","thread":"40","timestamp":"2024-11-29T15:18:45.312000Z"}
2024-11-29T15:18:45.315463269+00:00 stderr F {"component":"virt-launcher","level":"info","msg":"hostname: centos7-free-boa","subcomponent":"libvirt","thread":"40","timestamp":"2024-11-29T15:18:45.312000Z"}
2024-11-29T15:18:45.315463269+00:00 stderr F {"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Invalid machine ID in /var/lib/dbus/machine-id or /etc/machine-id","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"40","timestamp":"2024-11-29T15:18:45.312000Z"}
2024-11-29T15:18:45.315463269+00:00 stderr F {"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"40","timestamp":"2024-11-29T15:18:45.312000Z"}
2024-11-29T15:18:45.746754906+00:00 stderr F {"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:540","timestamp":"2024-11-29T15:18:45.746549Z"}
2024-11-29T15:18:45.764603426+00:00 stderr F {"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:539","timestamp":"2024-11-29T15:18:45.763112Z"}
2024-11-29T15:18:45.765772969+00:00 stderr F {"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2024-11-29T15:18:45.765544Z"}
~
```
i need help to solve this issue
