### ISSUE TITLE
Virtual machine exception after upgrading version

### ISSUE THREAD

**Issue by Itswag** [kubevirt/kubevirt#9707]
**What happened**:
When I upgraded from v0.58.1 to v0.59.0, the previous virtual machine was unable to start or create a new one.

**What you expected to happen**:
Normal upgrade iteration.

**How to reproduce it (as minimally and precisely as possible)**:
```
export KUBEVIRT_VERSION=v0.59.0
kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-operator.yaml
```

**Additional context**:
- virt-launcher-xxxx（Always restart indefinitely） logs
  ```
   {"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-05-06T03:53:07.374567Z"}
  
   {"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-05-06T03:53:07.374663Z"}
  
   {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:496","timestamp":"2023-05-06T03:53:07.375641Z"}
  
   {"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-05-06T03:53:07.376066Z"}
  
   {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:504","timestamp":"2023-05-06T03:53:07.376330Z"}
  
   panic: fork/exec /usr/sbin/virtqemud: errno 0
  
   
  
   goroutine 6 [running]:
  
   kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud.func1()
  
 	  pkg/virt-launcher/virtwrap/util/libvirt_helper.go:251 +0x4ce
  
   created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud
  
 	  pkg/virt-launcher/virtwrap/util/libvirt_helper.go:218 +0x65
  
   {"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:124","timestamp":"2023-05-06T03:53:07.382700Z"}
  
   {"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:142","timestamp":"2023-05-06T03:53:07.382945Z"}
  ```
- kubectl get vm -A
  ```
  NAMESPACE   NAME                       AGE    STATUS             READY
  vm          vm-3krqgvqb                43m    CrashLoopBackOff   False
  vm          vm-8lc86w8x                13d    CrashLoopBackOff   False
  vm          vm-c5ybecnppphmu1du5b9a    25d    CrashLoopBackOff   False
  vm          vm-pwopp42mffuq6muzl72rc   35d    CrashLoopBackOff   False
  vm          vm-qlijck6a                24d    CrashLoopBackOff   False

  ```
- kubectl describe vm vm-3krqgvqb -n vm
 ```
 Name:         vm-3krqgvqb
Namespace:    vm
Labels:       <none>
Annotations:  kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1alpha3
              vm.cloud/osType: Linux
API Version:  kubevirt.io/v1
Kind:         VirtualMachine
Metadata:
  Creation Timestamp:  2023-05-06T03:18:22Z
  Finalizers:
    kubevirt.io/virtualMachineControllerFinalize
  Generation:  1
  Managed Fields:
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:vm.cloud/osType:
      f:spec:
        .:
        f:dataVolumeTemplates:
        f:runStrategy:
        f:template:
          .:
          f:metadata:
            .:
            f:labels:
          f:spec:
            .:
            f:domain:
              .:
              f:clock:
                .:
                f:timer:
                  .:
                  f:hpet:
                    .:
                    f:present:
                  f:hyperv:
                  f:pit:
                    .:
                    f:tickPolicy:
                  f:rtc:
                    .:
                    f:tickPolicy:
                f:timezone:
              f:cpu:
                .:
                f:cores:
              f:devices:
                .:
                f:disks:
                f:interfaces:
              f:machine:
                .:
                f:type:
              f:memory:
                .:
                f:guest:
              f:resources:
                .:
                f:limits:
                  .:
                  f:cpu:
                  f:memory:
            f:networks:
            f:volumes:
    Manager:      true
    Operation:    Update
    Time:         2023-05-06T03:18:22Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
        f:finalizers:
          .:
          v:"kubevirt.io/virtualMachineControllerFinalize":
      f:status:
        .:
        f:conditions:
        f:printableStatus:
        f:startFailure:
          .:
          f:consecutiveFailCount:
          f:lastFailedVMIUID:
          f:retryAfterTimestamp:
        f:volumeSnapshotStatuses:
    Manager:         Go-http-client
    Operation:       Update
    Time:            2023-05-06T03:58:34Z
  Resource Version:  122559206
  UID:               2f3318c6-bcd4-4b95-8c31-87f3744ea335
Spec:
  Data Volume Templates:
    Metadata:
      Creation Timestamp:  <nil>
      Name:                vm-3krqgvqb-dv
    Spec:
      Pvc:
        Access Modes:
          ReadWriteOnce
        Resources:
          Requests:
            Storage:         30Gi
        Storage Class Name:  longhorn-test
      Source:
        Registry:
          URL:   docker://10.17.5.21/test/centos:7
  Run Strategy:  RerunOnFailure
  Template:
    Metadata:
      Creation Timestamp:  <nil>
      Labels:
        kubevirt.io/domain:  vm-3krqgvqb
    Spec:
      Domain:
        Clock:
          Timer:
            Hpet:
              Present:  false
            Hyperv:
            Pit:
              Tick Policy:  delay
            Rtc:
              Tick Policy:  catchup
          Timezone:         Asia/Shanghai
        Cpu:
          Cores:  2
        Devices:
          Disks:
            Disk:
              Bus:  virtio
            Name:   rootdisk
            Disk:
              Bus:  virtio
            Name:   cloudinitdisk
          Interfaces:
            Bridge:
            Name:  default
        Machine:
          Type:  q35
        Memory:
          Guest:  2Gi
        Resources:
          Limits:
            Cpu:     2
            Memory:  2Gi
      Networks:
        Name:  default
        Pod:
      Volumes:
        Data Volume:
          Name:  vm-3krqgvqb-dv
        Name:    rootdisk
        Cloud Init No Cloud:
          Network Data:  network:
  version: 1
  config:
  - type: physical
    name: eth0
    subnets:
      - type: dhcp
          User Data:  #cloud-config
ssh_pwauth: true
users:
  - name: root
    plain_text_passwd: 123456
    lock_passwd: false

        Name:  cloudinitdisk
Status:
  Conditions:
    Last Probe Time:       2023-05-06T03:58:34Z
    Last Transition Time:  2023-05-06T03:58:34Z
    Message:               VMI does not exist
    Reason:                VMINotExists
    Status:                False
    Type:                  Ready
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               cannot migrate VMI: PVC vm-3krqgvqb-dv is not shared, live migration requires that all PVCs must be shared (using ReadWriteMany access mode)
    Reason:                DisksNotLiveMigratable
    Status:                False
    Type:                  LiveMigratable
  Printable Status:        CrashLoopBackOff
  Start Failure:
    Consecutive Fail Count:  11
    Last Failed VMIUID:      1a7fa3a2-3f97-4fa4-9938-2284e87fb556
    Retry After Timestamp:   2023-05-06T04:03:34Z
  Volume Snapshot Statuses:
    Enabled:  false
    Name:     rootdisk
    Reason:   2 matching VolumeSnapshotClasses for longhorn-test
    Enabled:  false
    Name:     cloudinitdisk
    Reason:   Snapshot is not supported for this volumeSource type [cloudinitdisk]
Events:
  Type    Reason                      Age                  From                       Message
  ----    ------                      ----                 ----                       -------
  Normal  SuccessfulDataVolumeCreate  44m                  virtualmachine-controller  Created DataVolume vm-3krqgvqb-dv
  Normal  SuccessfulDelete            43m                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance ec2eefe6-e61e-4c92-8130-3f134d70bfe6
  Normal  SuccessfulDelete            42m                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance 84074a72-c638-4498-acc9-7c9ade448eff
  Normal  SuccessfulDelete            41m                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance cf77bf0a-e344-44a1-a66f-4c8bd85c9e39
  Normal  SuccessfulDelete            39m                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance 9d1331e4-e5d5-4cdb-84cc-6e8a09278b52
  Normal  SuccessfulDelete            35m                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance d57469f9-bf31-46d1-9677-1c604a384535
  Normal  SuccessfulDelete            31m                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance 7abbc59a-872b-4cc3-8b58-f514131245e0
  Normal  SuccessfulDelete            26m                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance 23ca58aa-62d1-4f61-a66d-9dc1143eee19
  Normal  SuccessfulDelete            20m                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance d86b5531-2333-402b-a945-f18a8cea96a6
  Normal  SuccessfulDelete            15m                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance b5c4076c-597d-43f7-a794-85ac5f22f7f8
  Normal  SuccessfulCreate            5m3s (x11 over 43m)  virtualmachine-controller  Started the virtual machine by creating the new virtual machine instance vm-3krqgvqb
  Normal  SuccessfulDelete            4m40s (x2 over 10m)  virtualmachine-controller  (combined from similar events): Stopped the virtual machine by deleting the virtual machine instance 1a7fa3a2-3f97-4fa4-9938-2284e87fb556
 ```
- virt-handler logs
 ```
  {"component":"virt-handler","level":"info","msg":"enabled device-plugins for: []","pos":"device_controller.go:322","timestamp":"2023-05-06T06:28:41.137364Z"}

 {"component":"virt-handler","level":"info","msg":"disabled device-plugins for: []","pos":"device_controller.go:323","timestamp":"2023-05-06T06:28:41.137401Z"}

 {"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: tun","pos":"generic_device.go:242","timestamp":"2023-05-06T06:29:12.866700Z"}

 {"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[tun474],}]","pos":"generic_device.go:243","timestamp":"2023-05-06T06:29:12.866804Z"}

 {"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: vhost-net","pos":"generic_device.go:242","timestamp":"2023-05-06T06:29:12.868709Z"}

 {"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[vhost-net231],}]","pos":"generic_device.go:243","timestamp":"2023-05-06T06:29:12.868829Z"}

 {"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: kvm","pos":"generic_device.go:242","timestamp":"2023-05-06T06:29:12.870163Z"}

 {"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[kvm693],}]","pos":"generic_device.go:243","timestamp":"2023-05-06T06:29:12.870194Z"}

 {"component":"virt-handler","level":"error","msg":"failed to remove mdev types: failed to read the content of /sys/bus/mdev/devices directory","pos":"mediated_devices_types.go:263","reason":"open /sys/bus/mdev/devices: no such file or directory","timestamp":"2023-05-06T06:30:40.325894Z"}

 {"component":"virt-handler","level":"info","msg":"refreshed device plugins for permitted/forbidden host devices","pos":"device_controller.go:321","timestamp":"2023-05-06T06:30:40.325937Z"}

 {"component":"virt-handler","level":"info","msg":"enabled device-plugins for: []","pos":"device_controller.go:322","timestamp":"2023-05-06T06:30:40.325948Z"}

 {"component":"virt-handler","level":"info","msg":"disabled device-plugins for: []","pos":"device_controller.go:323","timestamp":"2023-05-06T06:30:40.325957Z"}

 {"component":"virt-handler","level":"info","msg":"resyncing virt-launcher domains","pos":"cache.go:385","timestamp":"2023-05-06T06:31:03.996336Z"}

 {"component":"virt-handler","level":"error","msg":"failed to remove mdev types: failed to read the content of /sys/bus/mdev/devices directory","pos":"mediated_devices_types.go:263","reason":"open /sys/bus/mdev/devices: no such file or directory","timestamp":"2023-05-06T06:31:48.967743Z"}

 {"component":"virt-handler","level":"info","msg":"refreshed device plugins for permitted/forbidden host devices","pos":"device_controller.go:321","timestamp":"2023-05-06T06:31:48.967777Z"}

 {"component":"virt-handler","level":"info","msg":"enabled device-plugins for: []","pos":"device_controller.go:322","timestamp":"2023-05-06T06:31:48.967784Z"}

 {"component":"virt-handler","level":"info","msg":"disabled device-plugins for: []","pos":"device_controller.go:323","timestamp":"2023-05-06T06:31:48.967789Z"}

 {"component":"virt-handler","level":"error","msg":"failed to remove mdev types: failed to read the content of /sys/bus/mdev/devices directory","pos":"mediated_devices_types.go:263","reason":"open /sys/bus/mdev/devices: no such file or directory","timestamp":"2023-05-06T06:32:52.857091Z"}

 {"component":"virt-handler","level":"info","msg":"refreshed device plugins for permitted/forbidden host devices","pos":"device_controller.go:321","timestamp":"2023-05-06T06:32:52.857181Z"}

 {"component":"virt-handler","level":"info","msg":"enabled device-plugins for: []","pos":"device_controller.go:322","timestamp":"2023-05-06T06:32:52.857205Z"}

 {"component":"virt-handler","level":"info","msg":"disabled device-plugins for: []","pos":"device_controller.go:323","timestamp":"2023-05-06T06:32:52.857225Z"}

 {"component":"virt-handler","level":"error","msg":"failed to remove mdev types: failed to read the content of /sys/bus/mdev/devices directory","pos":"mediated_devices_types.go:263","reason":"open /sys/bus/mdev/devices: no such file or directory","timestamp":"2023-05-06T06:34:09.357975Z"}

 {"component":"virt-handler","level":"info","msg":"refreshed device plugins for permitted/forbidden host devices","pos":"device_controller.go:321","timestamp":"2023-05-06T06:34:09.358062Z"}

 {"component":"virt-handler","level":"info","msg":"enabled device-plugins for: []","pos":"device_controller.go:322","timestamp":"2023-05-06T06:34:09.358085Z"}

 {"component":"virt-handler","level":"info","msg":"disabled device-plugins for: []","pos":"device_controller.go:323","timestamp":"2023-05-06T06:34:09.358100Z"}


 ```
- Before this, I was unable to delete the virtual machine. The virtual machine has been in a Terminating state, and the kubectl delete command has been stuck. The status will only be updated by downgrading or upgrading the version

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`): v1.21.13
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): CentOS 7.9
- Kernel (e.g. `uname -a`): 3.10.0-1160.80.1.el7.x86_64
- Install tools: N/A
- Others: docker://20.10.12

**Comment by Itswag** [comment]
- virt-operator logs
 ```
  {"component":"virt-operator","level":"info","msg":"Kubevirt namespace (kubevirt) labels are in sync","pos":"core.go:58","timestamp":"2023-05-06T07:07:24.035355Z"}

 {"component":"virt-operator","kind":"","level":"info","msg":"All KubeVirt resources created","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:1081","timestamp":"2023-05-06T07:07:24.042106Z","uid":"99e20c7c-95c6-427f-a49e-4611df65292d"}

 {"component":"virt-operator","kind":"","level":"info","msg":"All KubeVirt components ready","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:1085","timestamp":"2023-05-06T07:07:24.042180Z","uid":"99e20c7c-95c6-427f-a49e-4611df65292d"}

 {"component":"virt-operator","kind":"","level":"error","msg":"Could not update the KubeVirt resource status.","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:684","reason":"Operation cannot be fulfilled on kubevirts.kubevirt.io \"kubevirt\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:07:24.049516Z","uid":"99e20c7c-95c6-427f-a49e-4611df65292d"}

 {"component":"virt-operator","level":"error","msg":"reenqueuing KubeVirt kubevirt/kubevirt","pos":"kubevirt.go:609","reason":"Operation cannot be fulfilled on kubevirts.kubevirt.io \"kubevirt\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:07:24.049568Z"}

 {"component":"virt-operator","kind":"","level":"info","msg":"Handling KubeVirt resource","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:657","timestamp":"2023-05-06T07:07:28.838288Z","uid":"99e20c7c-95c6-427f-a49e-4611df65292d"}

 {"component":"virt-operator","kind":"","level":"info","msg":"Handling deployment","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:1016","timestamp":"2023-05-06T07:07:28.838422Z","uid":"99e20c7c-95c6-427f-a49e-4611df65292d"}

 {"component":"virt-operator","level":"info","msg":"crd virtualmachinepools.pool.kubevirt.io updated","pos":"crds.go:61","timestamp":"2023-05-06T07:07:29.063301Z"}

 {"component":"virt-operator","level":"info","msg":"service kubevirt-prometheus-metrics patched","pos":"core.go:142","timestamp":"2023-05-06T07:07:29.073395Z"}

 {"component":"virt-operator","level":"info","msg":"service virt-api patched","pos":"core.go:142","timestamp":"2023-05-06T07:07:29.079503Z"}

 {"component":"virt-operator","level":"info","msg":"service kubevirt-operator-webhook patched","pos":"core.go:142","timestamp":"2023-05-06T07:07:29.086028Z"}

 {"component":"virt-operator","level":"info","msg":"service virt-exportproxy patched","pos":"core.go:142","timestamp":"2023-05-06T07:07:29.092726Z"}

 {"component":"virt-operator","level":"info","msg":"Kubevirt namespace (kubevirt) labels are in sync","pos":"core.go:58","timestamp":"2023-05-06T07:07:29.120190Z"}

 {"component":"virt-operator","kind":"","level":"info","msg":"All KubeVirt resources created","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:1081","timestamp":"2023-05-06T07:07:29.123326Z","uid":"99e20c7c-95c6-427f-a49e-4611df65292d"}

 {"component":"virt-operator","kind":"","level":"info","msg":"All KubeVirt components ready","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:1085","timestamp":"2023-05-06T07:07:29.123365Z","uid":"99e20c7c-95c6-427f-a49e-4611df65292d"}
 ```

**Comment by Itswag** [comment]
- virt-controller logs
 ```
  {"component":"virt-controller","kind":"","level":"error","msg":"Updating the VirtualMachine status failed.","name":"vm-8lc86w8x","namespace":"vm","pos":"vm.go:335","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-8lc86w8x\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:15.328279Z","uid":"f5850388-f2ce-415e-9022-2616abf7adb7"}

 {"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine vm/vm-8lc86w8x","pos":"vm.go:223","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-8lc86w8x\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:15.328340Z"}

 {"component":"virt-controller","kind":"","level":"error","msg":"Updating the VirtualMachine status failed.","name":"vm-8lc86w8x","namespace":"vm","pos":"vm.go:335","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-8lc86w8x\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:15.349314Z","uid":"f5850388-f2ce-415e-9022-2616abf7adb7"}

 {"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine vm/vm-8lc86w8x","pos":"vm.go:223","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-8lc86w8x\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:15.349396Z"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Starting VM due to runStrategy: Always","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:711","timestamp":"2023-05-06T07:15:26.300832Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Started VM by creating the new virtual machine instance vm-qlijck6a","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:946","timestamp":"2023-05-06T07:15:26.325473Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","kind":"","level":"error","msg":"Updating the VirtualMachine status failed.","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:335","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-qlijck6a\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:26.348313Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine vm/vm-qlijck6a","pos":"vm.go:223","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-qlijck6a\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:26.348384Z"}

 {"component":"virt-controller","kind":"","level":"error","msg":"Updating the VirtualMachine status failed.","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:335","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-qlijck6a\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:26.376931Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine vm/vm-qlijck6a","pos":"vm.go:223","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-qlijck6a\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:26.377009Z"}

 {"component":"virt-controller","kind":"","level":"error","msg":"Updating the VirtualMachine status failed.","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:335","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-qlijck6a\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:26.398283Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine vm/vm-qlijck6a","pos":"vm.go:223","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-qlijck6a\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:26.398347Z"}

 {"component":"virt-controller","kind":"","level":"error","msg":"Updating the VirtualMachine status failed.","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:335","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-qlijck6a\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:26.421670Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine vm/vm-qlijck6a","pos":"vm.go:223","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"vm-qlijck6a\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:26.421743Z"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Stopping VM with VMI in phase Failed and VM runStrategy: Always","name":"vm-8lc86w8x","namespace":"vm","pos":"vm.go:687","timestamp":"2023-05-06T07:15:33.959347Z","uid":"f5850388-f2ce-415e-9022-2616abf7adb7"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Dispatching delete event for vmi vm/vm-8lc86w8x with phase Failed","name":"vm-8lc86w8x","namespace":"vm","pos":"vm.go:1107","timestamp":"2023-05-06T07:15:33.967463Z","uid":"f5850388-f2ce-415e-9022-2616abf7adb7"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Stopping VM with VMI in phase Failed and VM runStrategy: Always","name":"vm-8lc86w8x","namespace":"vm","pos":"vm.go:687","timestamp":"2023-05-06T07:15:34.002326Z","uid":"f5850388-f2ce-415e-9022-2616abf7adb7"}

 {"component":"virt-controller","kind":"","level":"error","msg":"Updating the VirtualMachine status failed.","name":"vm-8lc86w8x","namespace":"vm","pos":"vm.go:335","reason":"the server rejected our request due to an error in our request","timestamp":"2023-05-06T07:15:34.011461Z","uid":"f5850388-f2ce-415e-9022-2616abf7adb7"}

 {"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine vm/vm-8lc86w8x","pos":"vm.go:223","reason":"the server rejected our request due to an error in our request","timestamp":"2023-05-06T07:15:34.011524Z"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Stopping VM with VMI in phase Failed and VM runStrategy: Always","name":"vm-8lc86w8x","namespace":"vm","pos":"vm.go:687","timestamp":"2023-05-06T07:15:34.011612Z","uid":"f5850388-f2ce-415e-9022-2616abf7adb7"}

 {"component":"virt-controller","level":"info","msg":"reenqueuing VirtualMachineInstance vm/vm-8lc86w8x","pos":"vmi.go:273","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"vm-8lc86w8x\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:34.016444Z"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Stopping VM with VMI in phase Failed and VM runStrategy: Always","name":"vm-8lc86w8x","namespace":"vm","pos":"vm.go:687","timestamp":"2023-05-06T07:15:34.016690Z","uid":"f5850388-f2ce-415e-9022-2616abf7adb7"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Delaying start of VM Starting VM with 'runStrategy: Always' due to start failure backoff. Waiting 290 more seconds before starting.","name":"vm-8lc86w8x","namespace":"vm","pos":"vm.go:706","timestamp":"2023-05-06T07:15:34.034017Z","uid":"f5850388-f2ce-415e-9022-2616abf7adb7"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Delaying start of VM Starting VM with 'runStrategy: Always' due to start failure backoff. Waiting 290 more seconds before starting.","name":"vm-8lc86w8x","namespace":"vm","pos":"vm.go:706","timestamp":"2023-05-06T07:15:34.045973Z","uid":"f5850388-f2ce-415e-9022-2616abf7adb7"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Stopping VM with VMI in phase Failed and VM runStrategy: Always","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:687","timestamp":"2023-05-06T07:15:49.700669Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Dispatching delete event for vmi vm/vm-qlijck6a with phase Failed","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:1107","timestamp":"2023-05-06T07:15:49.714901Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Stopping VM with VMI in phase Failed and VM runStrategy: Always","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:687","timestamp":"2023-05-06T07:15:49.752929Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","level":"info","msg":"reenqueuing VirtualMachineInstance vm/vm-qlijck6a","pos":"vmi.go:273","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"vm-qlijck6a\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-05-06T07:15:49.759973Z"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Delaying start of VM Starting VM with 'runStrategy: Always' due to start failure backoff. Waiting 300 more seconds before starting.","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:706","timestamp":"2023-05-06T07:15:49.782684Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","kind":"","level":"info","msg":"Delaying start of VM Starting VM with 'runStrategy: Always' due to start failure backoff. Waiting 300 more seconds before starting.","name":"vm-qlijck6a","namespace":"vm","pos":"vm.go:706","timestamp":"2023-05-06T07:15:49.794482Z","uid":"937d867d-8858-4c9f-b513-5be6eafb151a"}

 {"component":"virt-controller","level":"info","msg":"TSC Freqency node update status: 0 updated, 3 skipped, 0 errors","pos":"nodetopologyupdater.go:44","timestamp":"2023-05-06T07:15:57.608146Z"}

 {"component":"virt-controller","level":"info","msg":"TSC Freqency node update status: 0 updated, 3 skipped, 0 errors","pos":"nodetopologyupdater.go:44","timestamp":"2023-05-06T07:16:56.964134Z"}

 {"component":"virt-controller","level":"info","msg":"TSC Freqency node update status: 0 updated, 3 skipped, 0 errors","pos":"nodetopologyupdater.go:44","timestamp":"2023-05-06T07:17:43.469634Z"}

 {"component":"virt-controller","level":"info","msg":"TSC Freqency node update status: 0 updated, 3 skipped, 0 errors","pos":"nodetopologyupdater.go:44","timestamp":"2023-05-06T07:18:35.076547Z"}

 {"component":"virt-controller","level":"info","msg":"TSC Freqency node update status: 0 updated, 3 skipped, 0 errors","pos":"nodetopologyupdater.go:44","timestamp":"2023-05-06T07:19:35.528276Z"}
 ```

**Comment by caijian76** [comment]
I found out that v0.59 not support k8s with docker runtime.

**Comment by Itswag** [comment]
> I found out that v0.59 not support k8s with docker runtime. Try back version to v0.58.1

Yes, normal after rollback.
 #9465 #8619
