### ISSUE TITLE
After upgrading to v0.59.0 virt-launcher pod remains in notReady state when seLinux is in enforcing mode

### ISSUE THREAD

**Issue by kanikanema** [kubevirt/kubevirt#9728]
**What happened**:
Moved from kubevirt 0.58.1 to 0.59.0 and a VM can no longer be created. The virt-launcher pod remains in notReady and eventually moves to error state.
On the same setup with the same steps VM starts as expected when seLinux is set to permissive mode.

**What you expected to happen**:
VMs should start when seLinux is set to enforcing

**How to reproduce it (as minimally and precisely as possible)**:
1. Use kubevirt 0.59.0
2. seLinux is set to enforcing
3. Create a test vmi using the following yaml

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud2
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        name: default
  networks:
  - name: default
    pod: {}
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False } 

```

**Additional context**:
Featuregate 'Root' is enabled
Using containerd

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`): v1.24.9
- VM or VMI specifications: See above
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):  cat /etc/os-release 
```
NAME="Common Base Linux Mariner"
VERSION="2.0.20230426"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"

```
- Kernel (e.g. `uname -a`): 5.15.107.1-2.cm2 
- Install tools: N/A
- Others: N/A

virt-launcher logs with increased verbosity:

```
{"component":"virt-launcher","level":"info","msg":"Matched URI scheme 'qemu'","pos":"virConnectOpenInternal:1089","subcomponent":"libvirt","thread":"28","timestamp":"2023-05-08T09:06:23.965000Z"}
{"component":"virt-launcher","level":"info","msg":"driver 3 QEMU returned SUCCESS","pos":"virConnectOpenInternal:1129","subcomponent":"libvirt","thread":"28","timestamp":"2023-05-08T09:06:23.966000Z"}
{"component":"virt-launcher","level":"info","msg":"conn=0x735cd4013190","pos":"virConnectGetType:163","subcomponent":"libvirt","thread":"28","timestamp":"2023-05-08T09:06:23.967000Z"}
{"component":"virt-launcher","level":"info","msg":"dom=(nil), (VM: name=\u003cnull\u003e, uuid=), conn=0x735cd4013190, eventID=0, cb=0x59dacd082dc0, opaque=0x735d1c002e50, freecb=0x59dacd079400","pos":"virConnectDomainEventRegisterAny:9933","subcomponent":"libvirt","thread":"25","timestamp":"2023-05-08T09:06:24.181000Z"}{"component":"virt-launcher","level":"info","msg":"dom=(nil), (VM: name=\u003cnull\u003e, uuid=), conn=0x735cd4013190, eventID=19, cb=0x59dacd084b70, opaque=0x735cfc002610, freecb=0x59dacd079400","pos":"virConnectDomainEventRegisterAny:9933","subcomponent":"libvirt","thread":"32","timestamp":"2023-05-08T09:06:24.191000Z"}
...
"component":"virt-launcher","level":"info","msg":"conn=0x735cd4013190, domains=0x735d2320b8e0, flags=0x3","pos":"virConnectListAllDomains:6961","subcomponent":"libvirt","thread":"28","timestamp":"2023-05-08T09:11:04.270000Z"}
{"component":"virt-launcher","level":"info","msg":"Periodically checking for domain with UUID","pos":"virt-launcher.go:248","timestamp":"2023-05-08T09:11:14.265978Z"}
{"component":"virt-launcher","level":"info","msg":"conn=0x735cd4013190, domains=0x735d2420d8e0, flags=0x3","pos":"virConnectListAllDomains:6961","subcomponent":"libvirt","thread":"26","timestamp":"2023-05-08T09:11:14.269000Z"}
{"component":"virt-launcher","level":"info","msg":"Periodically checking for domain with UUID","pos":"virt-launcher.go:248","timestamp":"2023-05-08T09:11:24.272041Z"}
{"component":"virt-launcher","level":"info","msg":"conn=0x735cd4013190, domains=0x735d22a0a8e0, flags=0x3","pos":"virConnectListAllDomains:6961","subcomponent":"libvirt","thread":"29","timestamp":"2023-05-08T09:11:24.290000Z"}
panic: timed out waiting for domain to be defined

goroutine 1 [running]:
main.waitForDomainUUID(0xc0004b4660?, 0xc0004b4540, 0xc0002842a0, {0x1ce9698, 0xc0003141a0})
        cmd/virt-launcher/virt-launcher.go:246 +0x434
main.main()
        cmd/virt-launcher/virt-launcher.go:466 +0x1155


```

virt-handler logs

```
{"component":"virt-handler","level":"error","msg":"failed to create tap device named tap0","pos":"bridge.go:142","reason":"error creating tap device named tap0; failed to execute command in launcher namespace 14050: failed running command /usr/bin/virt-chroot create-tap --tap-name tap0 --uid 0 --gid 0 --queue-number 0 --mtu 1480, err: signal: segmentation fault, output: ","timestamp":"2023-05-08T10:33:26.870288Z"}
{"component":"virt-handler","level":"error","msg":"failed to configure pod network: eth0","pos":"configstate.go:74","timestamp":"2023-05-08T10:33:26.870469Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvmi-nocloud2","namespace":"default","pos":"vm.go:1830","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'eth0': Critical network error: error creating tap device named tap0; failed to execute command in launcher namespace 14050: failed running command /usr/bin/virt-chroot create-tap --tap-name tap0 --uid 0 --gid 0 --queue-number 0 --mtu 1480, err: signal: segmentation fault, output: ","timestamp":"2023-05-08T10:33:26.871882Z","uid":"a29d6dc7-785f-4fe4-8fa3-db4ab600c4f8"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of containerdisk volume","name":"testvmi-nocloud2","namespace":"default","pos":"vm.go:2349","timestamp":"2023-05-08T10:33:27.072495Z","uid":"a29d6dc7-785f-4fe4-8fa3-db4ab600c4f8"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of emptydisk volume","name":"testvmi-nocloud2","namespace":"default","pos":"vm.go:2349","timestamp":"2023-05-08T10:33:27.075219Z","uid":"a29d6dc7-785f-4fe4-8fa3-db4ab600c4f8"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of cloudinitdisk volume","name":"testvmi-nocloud2","namespace":"default","pos":"vm.go:2349","timestamp":"2023-05-08T10:33:27.075326Z","uid":"a29d6dc7-785f-4fe4-8fa3-db4ab600c4f8"}
{"component":"virt-handler","level":"error","msg":"virt-launcher crashed due to a network error. Updating VMI testvmi-nocloud2 status to Failed","pos":"vm.go:1246","timestamp":"2023-05-08T10:33:27.075516Z"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/testvmi-nocloud2","pos":"vm.go:1474","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'eth0': Critical network error: error creating tap device named tap0; failed to execute command in launcher namespace 14050: failed running command /usr/bin/virt-chroot create-tap --tap-name tap0 --uid 0 --gid 0 --queue-number 0 --mtu 1480, err: signal: segmentation fault, output: ","timestamp":"2023-05-08T10:33:27.326770Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"testvmi-nocloud2","namespace":"default","pos":"vm.go:1684","timestamp":"2023-05-08T10:33:27.326986Z","uid":"a29d6dc7-785f-4fe4-8fa3-db4ab600c4f8"}

```

selinux denials logged

```
type=PROCTITLE msg=audit(1683528436.764:1022): proctitle="(null)"
type=SYSCALL msg=audit(1683528436.764:1022): arch=c000003e syscall=59 success=no exit=-13 a0=c000ea7b60 a1=c0001a1490 a2=c00172c1e0 a3=0 items=0 ppid=7647 pid=12466 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="virt-chroot" exe="/usr/bin/virt-chroot" subj=system_u:system_r:container_t:s0:c471,c887 key=(null)
type=AVC msg=audit(1683528436.764:1022): avc:  denied  { use } for  pid=12466 comm="virt-chroot" path="/usr/bin/virt-chroot" dev="overlay" ino=2902392 scontext=system_u:system_r:container_t:s0:c471,c887 tcontext=system_u:system_r:spc_t:s0 tclass=fd permissive=0
type=AVC msg=audit(1683528436.764:1022): avc:  denied  { use } for  pid=12466 comm="virt-chroot" path="pipe:[80141]" dev="pipefs" ino=80141 scontext=system_u:system_r:container_t:s0:c471,c887 tcontext=system_u:system_r:spc_t:s0 tclass=fd permissive=0
type=AVC msg=audit(1683528436.764:1022): avc:  denied  { use } for  pid=12466 comm="virt-chroot" path="pipe:[80141]" dev="pipefs" ino=80141 scontext=system_u:system_r:container_t:s0:c471,c887 tcontext=system_u:system_r:spc_t:s0 tclass=fd permissive=0
type=AVC msg=audit(1683528436.764:1022): avc:  denied  { use } for  pid=12466 comm="virt-chroot" path="/dev/null" dev="tmpfs" ino=46 scontext=system_u:system_r:container_t:s0:c471,c887 tcontext=system_u:system_r:spc_t:s0 tclass=fd permissive=0
```

**Comment by xpivarc** [comment]
@maiqueb Can you have a look here?

**Comment by kanikanema** [comment]
Any pointers on what could be causing this issue?

**Comment by xpivarc** [comment]
/remove-lifecycle rotten
Hi @kanikanema ,
did you find any solution to this problem? 
/cc @jean-edouard

**Comment by kanikanema** [comment]
No, we couldn't. The only workaround we found was to set addition selinux policies for the denials that were reported. It looked like the seLinux policies in virt-laucher.cil weren't taking effect.

**Comment by jean-edouard** [comment]
This looks a lot like an `Fgetxattr`/`Fsetxattr` issue with the kernel of the nodes. The version is stated as `5.15.107.1-2.cm2` in some comment above.
@rmohr I think this is safepath-related, any chance you could have a look? Thanks!
