### ISSUE TITLE
Failed to create passt VM

### ISSUE THREAD

**Issue by qsliao** [kubevirt/kubevirt#9745]
**What happened**:

virt-launcher log is：
```
root@master:~/test/kubevirt# kubectl logs -f --tail 100 virt-launcher-vm1-passt-xxmw8
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqer.go:86","timestamp":"2023-05-16T07:07:27.894260Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-05-16T07:07:27.894375Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:519","timestamp":"2023-05-16T07:07:27.896072Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:527","timestamp":"2023-05-16T07:07:27.897050Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 9.0.0, package: 3.el9 (builder@centos.org, 2023-02-01-12:58:56, )","subcomponent":"libvirt","thread":"40","timestamp":"2023-05-16T07:07:27.924000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: vm1-passt","subcomponent":"libvirt","thread":"40","timestamp":"2023-05-16T07:07:27.924000Z"}
{"component":"virt-launcher","level":"error","msg":"Unable to open /dev/kvm: No such file or directory","pos":"virHostCPUGetCPUID:1422","subcomponent":"libvirt","thread":"40","timestamp":"2023-05-16T07:07:27.924000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"40","timestamp":"2023-05-16T07:07:27.925000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"40","timestamp":"2023-05-16T07:07:27.925000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:535","timestamp":"2023-05-16T07:07:28.401262Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:539","timestamp":"2023-05-16T07:07:28.406903Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2023-05-16T07:07:28.407409Z"}
{"component":"virt-launcher","level":"info","msg":"Hardware emulation device '/dev/kvm' not present. Using software emulation.","pos":"converter.go:1233","timestamp":"2023-05-16T07:07:30.769903Z"}
{"component":"virt-launcher","level":"info","msg":"In-kernel virtio-net device emulation '/dev/vhost-net' not present. Falling back to QEMU userland emulation.","pos":"converter.go:1991","timestamp":"2023-05-16T07:07:30.770041Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"vm1-passt","namespace":"default","pos":"manager.go:531","timestamp":"2023-05-16T07:07:30.770670Z","uid":"7f3d93f5-1fec-4f66-8cd1-4feb8de35c45"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"vm1-passt","namespace":"default","pos":"manager.go:552","timestamp":"2023-05-16T07:07:30.770735Z","uid":"7f3d93f5-1fec-4f66-8cd1-4feb8de35c45"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 52 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.783840Z"}
{"component":"virt-launcher","level":"info","msg":"passt: netlink: cannot set NETLINK_GET_STRICT_CHK on 4","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784047Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 44 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784078Z"}
{"component":"virt-launcher","level":"info","msg":"passt: No external routable interface for IPv6","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784095Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 36 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784111Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Outbound interface (IPv4): eth0","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784126Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 9 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784140Z"}
{"component":"virt-launcher","level":"info","msg":"passt: MAC:","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784154Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 32 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784168Z"}
{"component":"virt-launcher","level":"info","msg":"passt:     host: 00:00:00:aa:a8:5a","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784182Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 10 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784199Z"}
{"component":"virt-launcher","level":"info","msg":"passt: DHCP:","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784224Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 27 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784239Z"}
{"component":"virt-launcher","level":"info","msg":"passt:     assign: 10.16.0.37","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784257Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 26 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784272Z"}
{"component":"virt-launcher","level":"info","msg":"passt:     mask: 255.255.0.0","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784286Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 26 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784302Z"}
{"component":"virt-launcher","level":"info","msg":"passt:     router: 10.16.0.1","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784325Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 9 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784380Z"}
{"component":"virt-launcher","level":"info","msg":"passt: DNS:","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784420Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 19 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784452Z"}
{"component":"virt-launcher","level":"info","msg":"passt:     10.96.0.10","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784528Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 21 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784559Z"}
{"component":"virt-launcher","level":"info","msg":"passt: DNS search list:","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784586Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 34 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784614Z"}
{"component":"virt-launcher","level":"info","msg":"passt:     default.svc.cluster.local","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784645Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 26 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784676Z"}
{"component":"virt-launcher","level":"info","msg":"passt:     svc.cluster.local","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784717Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 22 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784746Z"}
{"component":"virt-launcher","level":"info","msg":"passt:     cluster.local","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.784827Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 53 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.789117Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 63 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.789233Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 124 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.789259Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 40 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.789277Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 64 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.789293Z"}
{"component":"virt-launcher","level":"info","msg":"passt: mount /: Permission denied","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.805244Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 40 bytes to syslog","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.805329Z"}
{"component":"virt-launcher","level":"error","msg":"failed waiting for passt going to background","pos":"generators.go:355","reason":"exit status 1","timestamp":"2023-05-16T07:07:30.858304Z"}
{"component":"virt-launcher","level":"fatal","msg":"failed to create libvirt configuration","pos":"podnic.go:234","reason":"exit status 1","timestamp":"2023-05-16T07:07:30.858453Z"}
panic: failed to create libvirt configuration

goroutine 98 [running]:
kubevirt.io/client-go/log.FilteredLogger.Critical({{0x1cd8fe0, 0xc000695480}, {0x1a42777, 0xd}, 0x0, 0x0, 0x2, 0x2, {0x1cdb220, 0xc00011c1e0}}, ...)
        staging/src/kubevirt.io/client-go/log/log.go:302 +0x194
kubevirt.io/kubevirt/pkg/network/setup.(*podNIC).PlugPhase2(0xc000197a78, 0x1d04218?)
        pkg/network/setup/podnic.go:234 +0x118
kubevirt.io/kubevirt/pkg/network/setup.(*VMNetworkConfigurator).SetupPodNetworkPhase2(0x17fcb00?, 0xc00025cae0?, {0xc000128500?, 0x18?, 0x0?})
        pkg/network/setup/network.go:94 +0x125
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).preStartHook(0xc00015a1a0, 0xc000020000, 0xc000020580, 0xa0?)
        pkg/virt-launcher/virtwrap/manager.go:580 +0x69b
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).SyncVMI(0xc00015a1a0, 0xc000020000, 0x0?, 0x0?)
        pkg/virt-launcher/virtwrap/manager.go:880 +0x345
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cmd-server.(*Launcher).SyncVirtualMachine(0xc0002da078, {0xc000120500?, 0x51e446?}, 0xc000120500)
        pkg/virt-launcher/virtwrap/cmd-server/server.go:184 +0x8a
kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1._Cmd_SyncVirtualMachine_Handler({0x19bfc20?, 0xc0002da078}, {0x1cf1480, 0xc00024f0e0}, 0xc0004b4ae0, 0x0)
        bazel-out/k8-fastbuild/bin/pkg/handler-launcher-com/cmd/v1/kubevirt_cmd_go_proto_/kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1/cmd.pb.go:2721 +0x173
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000041980, {0x1cf74b8, 0xc00038a300}, 0xc00057a000, 0xc000117320, 0x2a75940, 0x0)
        external/org_golang_google_grpc/server.go:1024 +0xd2f
google.golang.org/grpc.(*Server).handleStream(0xc000041980, {0x1cf74b8, 0xc00038a300}, 0xc00057a000, 0x0)
        external/org_golang_google_grpc/server.go:1313 +0xa16
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        external/org_golang_google_grpc/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        external/org_golang_google_grpc/server.go:720 +0xea
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:125","timestamp":"2023-05-16T07:07:30.865753Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:143","timestamp":"2023-05-16T07:07:30.866199Z"}
```
![image](https://github.com/kubevirt/kubevirt/assets/28948877/5ac7e663-7102-48d0-8c5d-51f421121934) 

the vm logs(kubectl describe vm vm1-passt):
![image](https://github.com/kubevirt/kubevirt/assets/28948877/fb08f770-6c4e-4b2a-a3ee-2f6f3d6bd0de)

**What you expected to happen**:

``` The virtual machine is powered on successfully  ```

**How to reproduce it (as minimally and precisely as possible)**:
```
1. Create a VM with a passt interface
2. Attempt to start the VM
3. The vm fails to start. Viewing pod virt-launcher-vm1-passt-xxmw8 logs： failed waiting for passt going to background
```
**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`):  v1.0.0
- Kubernetes version (use `kubectl version`): 1.27.1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release):  Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`):  Linux master 4.15.0-112-generic
- Install tools: N/A
- Others:

the vm config is:
```
root@master:~/test/kubevirt# cat vm1-passt.yaml 
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1-passt
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vm1-passt
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: red
            passt: {}
            ports:
            - port: 8080
              protocol: TCP
        resources:
          requests:
            memory: 64M
      networks:
      - name: red
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```

**Comment by sbrivio-rh** [comment]
@qsliao thanks for reporting this.

I'm not sure this has something to do with the issue, but, I wonder: do you have a particular reason to use a 7 years old version of Ubuntu (16.04) with a 5 years old kernel (4.15-ish), without (in your kernel configuration) support for KVM or virtio-net?

Maybe it should be supported -- I'm not claiming it's not, I'm not familiar with related requirements.

**Comment by qsliao** [comment]
Sorry, the os system is Ubuntu 18.04.5 LTS,  a VM  can be created  successfully  with the same image using slirp mode.  So I guess it's because libvirt doesn't support passt

**Comment by sbrivio-rh** [comment]
> libvirt doesn't support passt

It [does](https://libvirt.org/formatdomain.html#userspace-slirp-or-passt-connection), even though that integration is not used in KubeVirt yet.

The problem rather seems to be:
```
{"component":"virt-launcher","level":"info","msg":"passt: mount /: Permission denied","pos":"generators.go:340","timestamp":"2023-05-16T07:07:30.805244Z"}
```
which comes from the phase where passt is sandboxing itself, by remounting (in a detached mount namespace) its own / to an empty, zero-sized filesystem.

Why is this denied? If SELinux plays a role here, that might be something on the lines of this (fixed) [issue](https://github.com/containers/container-selinux/pull/196). But it's not clear to me where packages and policies come from in case you're running KubeVirt on Ubuntu -- is SELinux touching that at all?

The AppArmor [profile](https://passt.top/passt/tree/contrib/apparmor/abstractions/passt) already covers that, but it's not clear to me if the official Ubuntu [package](https://packages.ubuntu.com/mantic/passt) is used here -- I guess not, because you're on 18.04...?

Maybe somebody more familiar with the "packaging for KubeVirt" topic could shed some light? I'm looking at you, @andreabolognani and @AlonaKaplan :)

**Comment by andreabolognani** [comment]
The way workloads running inside containers interact with the host's AppArmor policy is still quite unclear to me.

The fact that a quite modern, RHEL-based userspace is running on top of a very old, Debian-based kernel and container runtime is probably not helping :)

Some of the information contained in [this document](https://kubevirt.io/user-guide/operations/installation/#integration-with-apparmor) might possibly prove useful.

**Comment by sbrivio-rh** [comment]
> Some of the information contained in [this document](https://kubevirt.io/user-guide/operations/installation/#integration-with-apparmor) might possibly prove useful.

Thanks for the pointer! @qsliao, would it be possible for you to have a look at that document and find out (there are some examples there) if host-side auditing logs say anything about the failed mount operation?

**Comment by qsliao** [comment]
I have uninstalled libvirtd and restarted the system by referring to [this document](https://kubevirt.io/user-guide/operations/installation/#integration-with-apparmor) but the following errors still occur when entering the "passt" command in pod, the following error will occur：
![image](https://github.com/kubevirt/kubevirt/assets/28948877/891ca419-e7a1-42aa-be76-2b383e74bb7a)

**Comment by qsliao** [comment]
virt-launcher logs  has no errors 

![image](https://github.com/kubevirt/kubevirt/assets/28948877/397013f1-0d35-4bfe-8d70-431d262d7cc4)

**Comment by qsliao** [comment]
The passt vm can be started successfully by adding the following annotation to the VM or VMI object:
annotations:
  container.apparmor.security.beta.kubernetes.io/compute: unconfined

**Comment by qsliao** [comment]
After selinux is installed, disable selinux can solve the problem:
```
sudo apt install selinux selinux-utils selinux-basics auditd -y
setenforce 0
sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config
reboot
```

**Comment by sbrivio-rh** [comment]
@qsliao great debugging, thanks. I wouldn't call that a solution, rather a workaround. It's actually the first time I see SELinux being used on a Debian-based distribution.

It would be really helpful if you could look at audit logs (it should be `/var/log/audit/audit.log` on Ubuntu), temporarily enable enforcing mode for SELinux (`setenforce 1`), start the VM, and check what's reported as failure for the `mount()` call in the log. Same with AppArmor.
